import UIKit
/// тип тренировки
enum Type: String {
    case beginner = "Новичок"
    case continuing = "Продолжающий" //добавила
    case advanced = "Продвинутый"    //добавила
  
}
/// модель тренировок 
struct Workouts {
    /// тип тренировки
    let type: Type
    /// картинка тренировки в главнном меню М
    let image: UIImage?
    /// картинка тренировки в главнном меню Ж
    let girlImage: UIImage?
    /// название тренировки
    let name: String
    /// массив упражнений в тренировке
    let lessons: [Lesson]
}

extension Workouts {
    static let test = Workouts(type: .continuing, image: UIImage(named: "begginerAbs"), girlImage: UIImage(named: "прессс"), name: "Test", lessons: [
        Lesson(name: "test1", time: 8, counts: nil, text: "Ноги вместе, руки вдоль корпуса. Прыжком разведите ноги, одновременно поднимаю руки в стороны до положения над головой. Прыжком верните в исходное положение. \n\nПовторите нужное количество раз. \n\nУпражнение нагружает все крупные группы мышц, укрепляя все тело.", imageBig: UIImage(named: "Jumping"), imageSmall: UIImage(named: "Прыжки")),
        Lesson(name: "test2", time: nil, counts: 16, text: "Лягте на спину, ноги согнуты в коленях. Приподнимаем корпус. \n\nЗадержитесь в верхнем положении на несколько секунд и медленно вернитесь в исходное положение. \n\nОсновная нагрузка приходится на прямую и косые мышцы живота.", imageBig: UIImage(named: "ExercisesForTheAbs"), imageSmall: UIImage(named: "Упражнения для пресса")),
        Lesson(name: "test3", time: 8, counts: nil, text: "Ноги вместе, руки вдоль корпуса. Прыжком разведите ноги, одновременно поднимаю руки в стороны до положения над головой. Прыжком верните в исходное положение. \n\nПовторите нужное количество раз. \n\nУпражнение нагружает все крупные группы мышц, укрепляя все тело.", imageBig: UIImage(named: "Jumping"), imageSmall: UIImage(named: "Прыжки"))
        ])

    // MARK: - Пресс новичок.

    static let beginnerabs = Workouts(type: .beginner, image: UIImage(named: "begginerAbs"), girlImage: UIImage(named: "прессс"), name: "Пресс", lessons: [
        Lesson(name: "Прыжки", time: 20, counts: nil, text: "Ноги вместе, руки вдоль корпуса. Прыжком разведите ноги, одновременно поднимаю руки в стороны до положения над головой. Прыжком верните в исходное положение. \n\nПовторите нужное количество раз. \n\nУпражнение нагружает все крупные группы мышц, укрепляя все тело.", imageBig: UIImage(named: "Jumping"), imageSmall: UIImage(named: "Прыжки")),
        Lesson(name: "Упражнения для пресса", time: nil, counts: 16, text: "Лягте на спину, ноги согнуты в коленях. Приподнимаем корпус. \n\nЗадержитесь в верхнем положении на несколько секунд и медленно вернитесь в исходное положение. \n\nОсновная нагрузка приходится на прямую и косые мышцы живота.", imageBig: UIImage(named: "ExercisesForTheAbs"), imageSmall: UIImage(named: "Упражнения для пресса")),
        Lesson(name: "Качели", time: nil, counts: 20, text: "Сядьте на пол, согните колени. Ноги слегка приподнять, корпус отклонить назад. \n\nСоедините руки перед грудью и делайте повороты корпуса из стороны в сторону.", imageBig: UIImage(named: "Swing"), imageSmall: UIImage(named: "Качели")),
        Lesson(name: "Альпинист", time: nil, counts: 16, text: "Примите упор лежа. Подтяните правое колено к груди, выпрыгните и поменяйте в воздухе ноги – левую вперед, правую назад. \n\nУкрепляет многие группы мышц, полезно для сердечно-сосудистой системы.", imageBig: UIImage(named: "Mountaineer"), imageSmall: UIImage(named: "Альпинист")),
        Lesson(name: "Боковые наклоны к стопам", time: nil, counts: 20, text: "Ложитесь на спину, ноги согните в коленях, руки лежат вдоль корпуса. \n\nПриподнимите корпус от пола и поочередно касайтесь пятки пальцами той же руки.", imageBig: UIImage(named: "SideBendsTheFeet"), imageSmall: UIImage(named: "icons8-sit-ups-96")),
        Lesson(name: "Поднятие ног лежа на спине", time: nil, counts: 16, text: "Лягте на спину и положите руки под бедра для поддержки. \n\nПоднимите прямые ноги вверх до образования прямого угла с полом.Медленно опустите ноги вниз и повторите упражнение.", imageBig: UIImage(named: "LegRaisesLyingOnBack"), imageSmall: UIImage(named: "Поднятие ног лежа на спине")),
        Lesson(name: "Планка", time: 20, counts: nil, text: "Удерживайте положение «упор лежа» на локтях и пальцах ног. \n\nПытайтесь сохранить это положение с прямой спиной. \n\nУпражнение укрепляет мышцы живота, спины и плеч.", imageBig: UIImage(named: "Plank"), imageSmall: UIImage(named: "Планка")),
        Lesson(name: "Упражнения для пресса", time: nil, counts: 12, text: "Лягте на спину, ноги согнуты в коленях, руки вытянуты вперед. Приподнимите корпус. \n\nЗадерживайтесь в верхнем положение на несколько секунд и медленно вернитесь в исходное положение. \n\nОсновная нагрузка приходится на прямую и косые мышцы живота.", imageBig: UIImage(named: "ExercisesForTheAbs"), imageSmall: UIImage(named: "Упражнения для пресса")),
        Lesson(name: "Качели", time: nil, counts: 32, text: "Сядьте на пол, согните колени. Ноги слегка приподнять, корпус отклонить назад. \n\nСоедините руки перед грудью и делайте повороты корпуса из стороны в сторону.", imageBig: UIImage(named: "Swing"), imageSmall: UIImage(named: "Качели")),
        Lesson(name: "Альпинист", time: nil, counts: 12, text: "Примите упор лежа. Подтяните правое колено к груди, выпрыгните и поменяйте в воздухе ноги – левую вперед, правую назад. \n\nУкрепляет многие группы мышц, полезно для сердечно-сосудистой системы.", imageBig: UIImage(named: "Mountaineer"), imageSmall: UIImage(named: "Альпинист")),
        Lesson(name: "Боковые наклоны к стопам", time: nil, counts: 20, text: "Ложитесь на спину, ноги согните в коленях, руки лежат вдоль корпуса. \n\nПриподнимите корпус от пола и поочередно касайтесь пятки пальцами той же руки.", imageBig: UIImage(named: "SideBendsTheFeet"), imageSmall: UIImage(named: "icons8-sit-ups-96")),
        Lesson(name: "Поднятие ног лежа на спине", time: nil, counts: 14, text: "Лягте на спину и положите руки под бедра для поддержки. \n\nПоднимите прямые ноги вверх до образования прямого угла с полом.Медленно опустите ноги вниз и повторите упражнение.", imageBig: UIImage(named: "LegRaisesLyingOnBack"), imageSmall: UIImage(named: "Поднятие ног лежа на спине")),
        Lesson(name: "Планка", time: 30, counts: nil, text: "Удерживайте положение «упор лежа» на локтях и пальцах ног. \n\nПытайтесь сохранить это положение с прямой спиной. \n\nУпражнение укрепляет мышцы живота, спины и плеч.", imageBig: UIImage(named: "Plank"), imageSmall: UIImage(named: "Планка")),
        Lesson(name: "Растяжка «кобра»", time: 30, counts: nil, text: "Ложитесь на живот. Руки согнуты в локтях, ладони на полу под плечами. \n\nПоднимите грудь как можно выше над полом. Оставайтесь в этом положении несколько секунд.", imageBig: UIImage(named: "CobraStretch"), imageSmall: UIImage(named: "Растяжка «кобра»")),
        Lesson(name: "Скручивания в пояснице лежа на полу (влево)", time: 30, counts: nil, text: "Ложитесь на спину, ноги вытянуты. \n\nПоднимите левую ногу и потяните ее за колено правой рукой в правую сторону.Оставайтесь в этом положении несколько секунд.", imageBig: UIImage(named: "LumbarCurlsLyingOnTheFloor (toTheLeft)"), imageSmall: UIImage(named: "Скручивания в пояснице лежа на полу")),
        Lesson(name: "Скручивания в пояснице лежа на полу (вправо)", time: 30, counts: nil, text: "Ложитесь на спину, ноги вытянуты. \n\nПоднимите правую ногу и потяните ее за колено левой рукой в левую сторону.Оставайтесь в этом положении несколько секунд.", imageBig: UIImage(named: "LumbarCurlsLyingOnTheFloor (toTheRight)"), imageSmall: UIImage(named: "Скручивания в пояснице лежа на полу"))
    ])
    // MARK: - Грудь новичок.
    ///грудь новичок
    static let beginnerchest = Workouts(type: .beginner, image: UIImage(named: "beginnerChest"), girlImage: UIImage(named: "грудь"), name: "Грудь", lessons: [
        Lesson(name: "Прыжки", time: 30, counts: nil, text: "Ноги вместе, руки вдоль корпуса. Прыжком разведите ноги, одновременно поднимаю руки в стороны до положения над головой. Прыжком верните в исходное положение. \n\nПовторите нужное количество раз. Упражнение нагружает все крупные группы мышц, укрепляя все тело.", imageBig: UIImage(named: "Jumping"), imageSmall: UIImage(named: "Прыжки")),
        Lesson(name: "Отжимания с опорой впереди", time: nil, counts: 16, text: "Исходное положение – обычное положение для отжиманий, но с руками на стуле или скамье. \n\nВыполняйте отжимания силой рук. Не забывайте держать корпус прямо.", imageBig: UIImage(named: "FrontPushUp"), imageSmall: UIImage(named: "Отжимания с опорой впереди")),
        Lesson(name: "Отжимания с упором на колени", time: nil, counts: 12, text: "Исходное положение – обычное положение для отжиманий, но с упором на колени и приподнятыми стопами. Выполняйте отжимания.", imageBig: UIImage(named: "KneeBasedPushUps"), imageSmall: UIImage(named: "Отжимания с упором на колени")),
        Lesson(name: "Отжимания от пола", time: nil, counts: 10, text: "Поднятие и опускание тела с помощью рук, держите тело прямо. \n\nЭто упражнения прорабатывает мышцы груди, плеч, трицепса, спину и ноги.", imageBig:
                UIImage(named: "FloorPushUps"), imageSmall: UIImage(named: "Отжимания от пола")),
        Lesson(name: "Отжимания с широким упором", time: nil, counts: 10, text: "Исходное положение – обычное положение для отжиманий, но с упором шире плеч. \n\nВыполняйте отжимания. Не забывайте держать корпус прямо.", imageBig: UIImage(named: "PushupsWithWideSupport"), imageSmall: UIImage(named: "Отжимания с широким упором")),
        Lesson(name: "Отжимания с упором на колени", time: nil, counts: 12, text: "Исходное положение – обычное положение для отжиманий, но с упором на колени и приподнятыми стопами. Выполняйте отжимания.", imageBig: UIImage(named: "KneeBasedPushUps"), imageSmall: UIImage(named: "Отжимания с упором на колени")),
        Lesson(name: "Отжимания с широким упором", time: nil, counts: 10, text: "Исходное положение – обычное положение для отжиманий, но с упором шире плеч. \n\nВыполняйте отжимания. Не забывайте держать корпус прямо.", imageBig: UIImage(named: "PushupsWithWideSupport"), imageSmall: UIImage(named: "Отжимания с широким упором")),
        Lesson(name: "Отжимания по-индийски", time: nil, counts: 10, text: "Исходно положение – руки и ноги касаются пола, бедра подтянуты вверх. Положение напоминает перевернутую букву «V». \n\nСогните руки в локтях, опуская тело к полу. Когда тело будет близко к полу, поднимите корпус как можно выше. \n\nЗатем вернитесь в исходное положение и повторите упражнение.", imageBig: UIImage(named: "IndianStylePushups"), imageSmall: UIImage(named: "Отжимания по-индийски")),
        Lesson(name: "Растяжка «кобра»", time: 20, counts: nil, text: "Ложитесь на живот. Руки согнуты в локтях, ладони на полу под плечами. \n\nПоднимите грудь как можно выше над полом. Оставайтесь в этом положении несколько секунд.", imageBig: UIImage(named: "CobraStretch"), imageSmall: UIImage(named: "Растяжка «кобра»")),
        Lesson(name: "Грудь", time: 20, counts: nil, text: "Встаньте в дверной проем в положении выпада, положив предплечья по сторонам на дверной косяк, локти чуть ниже плеч. Затем медленно подайте грудь вперед. \n\nОставайтесь в этом положении 20 секунд. Затем медленно отведите грудь назад в исходное положение, опустите руки и сделайте несколько вращательных движений плечами назад.", imageBig: UIImage(named: "Chest"), imageSmall: UIImage(named: "Грудь"))
    ])
    // MARK: - Руки новичок.
    ///Руки новичок    
    static let beginnerarms = Workouts(type: .beginner, image: UIImage(named: "beginnerArms"), girlImage: UIImage(named: "руки"), name: "Руки", lessons: [
        Lesson(name: "Вращение руками", time: 30, counts: nil, text: "Встаньте на пол, вытянув прямые руки вперед на высоте плеч. \n\nПоднимите руки нал головой, затем вернитесь в исходное положение. Повторите упражнение.", imageBig: UIImage(named: "RotationOfTheArms"), imageSmall: UIImage(named: "icons8-йога-96 1")),
        Lesson(name: "Подъем рук в сторону", time: 30, counts: nil, text: "Встаньте ровно, ноги на ширине плеч. \n\nПоднимите руки в стороны до уровня плеч.Поднимите руки в стороны до уровня плеч, а затем опустите. Повторите упражнение.", imageBig: UIImage(named: "ArmsOutToTheSide"), imageSmall: UIImage(named: "Подъем рук в сторону")),
        Lesson(name: "Обратные отжимания от стула", time: nil, counts: 10, text: "В положении спиной к стулу обопритесь о переднюю часть стула, при этом отодвинув бедра и ноги. \n\nДержа спину близко к стулу, согните локти до угла 90 градусов. \n\nЭто отличное упражнение для трицепсов.", imageBig: UIImage(named: "ReversePushUps "), imageSmall: UIImage(named: "Обратные отжимания от стула")),
        Lesson(name: "Махи руками по часовой стрелке", time: 30, counts: nil, text: "Встаньте ровно, руки вытянуты в стороны на уровне плеч. \n\nБыстро вращайте руками от плеч по часовой стрелке.", imageBig: UIImage(named: "HandSwings"), imageSmall: UIImage(named: "Грудь")),
        Lesson(name: "Махи руками против часовой стрелке ", time: 30, counts: nil, text: "Встаньте ровно, руки вытянуты в стороны на уровне плеч. \n\nБыстро вращайте руками от плеч против  часовой стрелке.", imageBig: UIImage(named: "HandSwings"), imageSmall: UIImage(named: "Грудь")),
        Lesson(name: "Отжимания со сведенными ладонями", time: nil, counts: 6, text: "Примите упор лежа, как при отжимания. \n\nСоедините большие и указательные пальцы рук под грудью в форме алмаза и выполните отжимания. \n\nНе забывайте держать корпус прямо.", imageBig: UIImage(named: "Push-upsWithPalmsTogether"), imageSmall: UIImage(named: "Отжимания с опорой впереди")),
        Lesson(name: "Прыжки", time: 30, counts: nil, text: "Ноги вместе, руки вдоль корпуса. Прыжком разведите ноги, одновременно поднимаю руки в стороны до положения над головой. Прыжком верните в исходное положение. \n\nПовторите нужное количество раз. Упражнение нагружает все крупные группы мышц, укрепляя все тело.", imageBig: UIImage(named: "Jumping"), imageSmall: UIImage(named: "Прыжки")),
        Lesson(name: "Диагональная «планка»", time: nil, counts: 10, text: "Исходное положение – «планка» на прямых руках. Поднимите правую руку и левую ногу параллельно полу. \n\nВернитесь в исходное положение и повторите на другую сторону.", imageBig: UIImage(named: "DiagonalBar"), imageSmall: UIImage(named: "Диагональная «планка»")),
        Lesson(name: "Отжимания от пола", time: nil, counts: 10, text: "Поднятие и опускание тела с помощью рук, держите тело прямо. \n\nЭто упражнения прорабатывает мышцы груди, плеч, трицепса, спину и ноги.", imageBig: UIImage(named: "FloorPushUps"), imageSmall: UIImage(named: "Отжимания от пола")),
        Lesson(name: "Гусеница", time: nil, counts: 8, text: "Ноги на ширине плеч. Согните корпус и идите на руках вперед так далеко, как сможете, затем вернитесь на руках обратно. Повторите упражнения.", imageBig: UIImage(named: "Caterpillar"), imageSmall: UIImage(named: "icons8-приседания")),
        Lesson(name: "Отжимания от стены", time: nil, counts: 12, text: "Встаньте перед стеной на расстоянии широкого шага. Вытяните руки прямо перед собой и упритесь о стену. Поднимите пятки. \n\nМедленно согните руки в локтях, приближая корпус к стене. \n\nОтожмитесь и повторите упражнение.На забывайте держать корпус прямо.", imageBig: UIImage(named: "WallPushUps"), imageSmall: UIImage(named: "icons8-планка.pdf"))
    ])
    // MARK: - Ноги новичок.
    /// ноги новичок
    static let beginnerlegs = Workouts(type: .beginner, image: UIImage(named: "beginnerLegs"), girlImage: UIImage(named: "ноги"), name: "Ноги", lessons: [
        Lesson(name: "Прыжки в сторону", time: 30, counts: nil, text: "Встаньте ровно, руки перед собой, и делайте прыжки в стороны.", imageBig: UIImage(named: "SideJumps"), imageSmall: UIImage(named: "Прыжки")),
        Lesson(name: "Приседания", time: nil, counts: 12, text: "Ноги на ширине плеч, руки вытянуты перед собой. Опускайтесь до тех пор, пока бедра не будут параллельно полу. \n\nПри выполнении упражнения колени должны быть направлены туда же, куда направлены носки ног. Вернитесь в исходное положение.Повторите нужное количество раз. \n\nУпражнение нагружает мышцы передней и задней поверхности бедра, ягодицы, нижней части корпуса.", imageBig: UIImage(named: "Squats"), imageSmall: UIImage(named: "Приседания")),
        Lesson(name: "Приседания", time: nil, counts: 12, text: "Ноги на ширине плеч, руки вытянуты перед собой. Опускайтесь до тех пор, пока бедра не будут параллельно полу. \n\nПри выполнении упражнения колени должны быть направлены туда же, куда направлены носки ног. Вернитесь в исходное положение.Повторите нужное количество раз. \n\nУпражнение нагружает мышцы передней и задней поверхности бедра, ягодицы, нижней части корпуса.", imageBig: UIImage(named: "Squats"), imageSmall: UIImage(named: "Приседания")),
        Lesson(name: "Подъем ноги лёжа на боку (для левой ноги)", time: nil, counts: 12, text: "Лягте на бок, подложив вправо руку под голову. \n\nПоднимите верхнюю ногу и вернитесь в исходное положение.Выполнив упражнение несколько раз, перевернитесь на другой бок. \n\nСовет: старайтесь поднимать и опускать прямую ногу.Мышцы: ягодичные.", imageBig: UIImage(named: "SideLegRaise(forLeftLeg)"), imageSmall: UIImage(named: "plank")),
        Lesson(name: "Подъем ноги лёжа на боку (для правой ноги)", time: nil, counts: 12, text: "Лягте на бок, подложив вправо руку под голову. \n\nПоднимите верхнюю ногу и вернитесь в исходное положение.Выполнив упражнение несколько раз, перевернитесь на другой бок. \n\nСовет: старайтесь поднимать и опускать прямую ногу.Мышцы: ягодичные.", imageBig: UIImage(named: "SideLegRaise(forRightLeg)"), imageSmall: UIImage(named: "plank")),
        Lesson(name: "Подъем ноги лёжа на боку (для левой ноги)", time: nil, counts: 12, text: "Лягте на бок, подложив вправо руку под голову. \n\nПоднимите верхнюю ногу и вернитесь в исходное положение.Выполнив упражнение несколько раз, перевернитесь на другой бок. \n\nСовет: старайтесь поднимать и опускать прямую ногу.Мышцы: ягодичные.", imageBig: UIImage(named: "SideLegRaise(forLeftLeg)"), imageSmall: UIImage(named: "plank")),
        Lesson(name: "Подъем ноги лёжа на боку (для правой ноги)", time: nil, counts: 12, text: "Лягте на бок, подложив вправо руку под голову. \n\nПоднимите верхнюю ногу и вернитесь в исходное положение.Выполнив упражнение несколько раз, перевернитесь на другой бок. \n\nСовет: старайтесь поднимать и опускать прямую ногу.Мышцы: ягодичные.", imageBig: UIImage(named: "SideLegRaise(forRightLeg)"), imageSmall: UIImage(named: "plank")),
        Lesson(name: "Выпад назад", time: nil, counts: 14, text: "Встаньте ровно, ноги на ширине плеч, руки на бедрах. \n\nСделайте большой шаг назад правой ногой, опускаясь всем телом так, чтобы левое бедро было параллельно полу. n\nВернитесь в исходное положение и повторите упражнения в другую сторон.", imageBig: UIImage(named: "BackLunge"), imageSmall: UIImage(named: "icons8-stretching-96")),
        Lesson(name: "Выпад назад", time: nil, counts: 14, text: "Встаньте ровно, ноги на ширине плеч, руки на бедрах. \n\nСделайте большой шаг назад правой ногой, опускаясь всем телом так, чтобы левое бедро было параллельно полу. \n\nВернитесь в исходное положение и повторите упражнения в другую сторону.", imageBig: UIImage(named: "BackLunge"), imageSmall: UIImage(named: "icons8-stretching-96")),
        Lesson(name: "Ослик лягается влево", time: nil, counts: 16, text: "И.п. стоя на четвереньках, колени строго под бедрами, руки под плечи. \n\nВытяните левую ногу в сторону, максимально развернув колено вверх.", imageBig: UIImage(named: "DonkeyKickToTheLeft"), imageSmall: UIImage(named: "Ослик лягается")),
        Lesson(name: "Ослик лягается вправо", time: nil, counts: 16, text: "И.п. стоя на четвереньках, колени строго под бедрами, руки под плечи. \n\nВытяните правую ногу в сторону, максимально развернув колено вверх.", imageBig: UIImage(named: "DonkeyKickToTheRight"), imageSmall: UIImage(named: "Ослик лягается")),
        Lesson(name: "Ослик лягается влево", time: nil, counts: 16, text: "И.п. стоя на четвереньках, колени строго под бедрами, руки под плечи. \n\nВытяните левую ногу в сторону, максимально развернув колено вверх.", imageBig: UIImage(named: "DonkeyKickToTheLeft"), imageSmall: UIImage(named: "Ослик лягается")),
        Lesson(name: "Ослик лягается вправо", time: nil, counts: 16, text: "И.п. стоя на четвереньках, колени строго под бедрами, руки под плечи. \n\nВытяните правую ногу в сторону, максимально развернув колено вверх.", imageBig: UIImage(named: "DonkeyKickToTheRight"), imageSmall: UIImage(named: "Ослик лягается")),
        Lesson(name: "Растяжка четырехглавой мышцы у стены (левая нога)", time: 30, counts: nil, text: "Встаньте ровно, правая рука на стене. Согните левую ногу в колене и обхватите щиколотку или ступню левой рукой. \n\nПодтяните левую голень к левому бедру. Оставайтесь в этом положении.", imageBig: UIImage(named: "Stretch(left leg)"), imageSmall: UIImage(named: "Растяжка четырехглавой")),
        Lesson(name: "Растяжка четырехглавой мышцы у стены (правая нога)", time: 30, counts: nil, text: "Встаньте ровно, левая рука на стене. Согните правую ногу в колене и обхватите щиколотку или ступню правой  рукой. \n\nПодтяните правую голень к правому бедру. Оставайтесь в этом положении.", imageBig: UIImage(named: "Stretch(right leg)"), imageSmall: UIImage(named: "Растяжка четырехглавой")),
        Lesson(name: "Растяжка «левое колено к груди»", time: 30, counts: nil, text: "Ложитесь спиной на пол, ноги вытянуты. Поднимите левое колено и схватите его обеими руками. \n\nПотяните левое колено как можно ближе к груди, прямая правая нога при этом должна лежать на полу.Оставайтесь в этом положении несколько секунд.", imageBig: UIImage(named: "LeftKneeToChestStretch"), imageSmall: UIImage(named: "workout-5")),
        Lesson(name: "Растяжка «правое колено к груди»", time: 30, counts: nil, text: "Ложитесь спиной на пол, ноги вытянуты. Поднимите правое колено и схватите его обеими руками. \n\nПотяните правое колено как можно ближе к груди, прямая левая нога при этом должна лежать на полу.Оставайтесь в этом положении несколько секунд.", imageBig: UIImage(named: "RightKneeToChestStretch"), imageSmall: UIImage(named: "workout-5"))
    ])
    // MARK: - Плечи и спина новичок.
    /// Плечи и спина новичок // beginnerShouldersAndBack +фото
    static let beginnerShouldersAndBack = Workouts(type: .beginner, image: UIImage(named: "beginnerShouldersAndBack"), girlImage: UIImage(named: "спина"), name: "Плечи и спина", lessons: [
        Lesson(name: "Прыжки", time: 30, counts: nil, text: "Ноги вместе, руки вдоль корпуса. Прыжком разведите ноги, одновременно поднимаю руки в стороны до положения над головой. Прыжком верните в исходное положение. \n\nПовторите нужное количество раз. \n\nУпражнение нагружает все крупные группы мышц, укрепляя все тело.", imageBig: UIImage(named: "Jumping"), imageSmall: UIImage(named: "Прыжки")),
        Lesson(name: "Вращение руками", time: 16, counts: nil, text: "Встаньте на пол, вытянув прямые руки вперед на высоте плеч. \n\nПоднимите руки нал головой, затем вернитесь в исходное положение. Повторите упражнение.", imageBig: UIImage(named: "RotationOfTheArms"), imageSmall: UIImage(named: "icons8-йога-96 1")),
        Lesson(name: "Подъем рук в сторону ", time: 16, counts: nil, text: "Встаньте ровно, ноги на ширине плеч. \n\nПоднимите руки в стороны до уровня плеч.Поднимите руки в стороны до уровня плеч, а затем опустите. \n\nПовторите упражнение.", imageBig: UIImage(named: "ArmsOutToTheSide"), imageSmall: UIImage(named: "Подъем рук в сторону")),
        Lesson(name: "Отжимания с упором на колени", time: nil, counts: 14, text: "Исходное положение – обычное положение для отжиманий, но с упором на колени и приподнятыми стопами. Выполняйте отжимания.", imageBig: UIImage(named: "KneeBasedPushUps"), imageSmall: UIImage(named: "Отжимания с упором на колени")),
        Lesson(name: "Ножницы руками", time: 30, counts: nil, text: "Встаньте ровно, ноги на ширине плеч. \n\nВытяните руки перед собой на уровне плеч, так, чтобы одна была чуть выше другой, а вместе они составляли букву «Х». \n\nЗатем разведите руки в стороны.Повторите упражнение так, чтобы теперь выше была другая рука.", imageBig: UIImage(named: "ScissorHands"), imageSmall: UIImage(named: "exercise-4")),
        Lesson(name: "Подъем рук в сторону", time: 14, counts: nil, text: "Встаньте ровно, ноги на ширине плеч. \n\nПоднимите руки в стороны до уровня плеч.Поднимите руки в стороны до уровня плеч, а затем опустите. \n\nПовторите упражнение.", imageBig: UIImage(named: "ArmsOutToTheSide"), imageSmall: UIImage(named: "Подъем рук в сторону")),
        Lesson(name: "Отжимания с упором на колени", time: nil, counts: 14, text: "Исходное положение – обычное положение для отжиманий, но с упором на колени и приподнятыми стопами. Выполняйте отжимания.", imageBig: UIImage(named: "KneeBasedPushUps"), imageSmall: UIImage(named: "Отжимания с упором на колени")),
        Lesson(name: "Поза кошки", time: 30, counts: nil, text: "Начальное положение – на четвереньках, колени под ягодицами, ладони прямо под плечами. \n\nДелая вдох, опустите живот, разверните плечи и поднимите голову. \n\nДелая выдох, выгните спину наверх и опустите голову. Повторите упражнение.", imageBig: UIImage(named: "CatPose"), imageSmall: UIImage(named: "yoga-pose-2")),
        Lesson(name: "Полуотжимания на трицепсы", time: nil, counts: 14, text: "Ложитесь на живот, поставьте ладони на пол прямо под плечи, локти согнуты. \n\nМедленно поднимите грудь от пола, затем вернитесь в исходное положение. Повторите упражнение.", imageBig: UIImage(named: "TricepsPushUps"), imageSmall: UIImage(named: "icons8-трицепс-96")),
        Lesson(name: "Полуотжимания на трицепсы", time: nil, counts: 14, text: "Ложитесь на живот, поставьте ладони на пол прямо под плечи, локти согнуты. \n\nМедленно поднимите грудь от пола, затем вернитесь в исходное положение. Повторите упражнение.", imageBig: UIImage(named: "TricepsPushUps"), imageSmall: UIImage(named: "icons8-трицепс-96")),
        Lesson(name: "Поза ребенка", time: 30, counts: nil, text: "Начальное положение – с коленями и ладонями на полу. \n\nСлегка вытяните руки вперед, раздвиньте колени и сведите вместе ступни. Вдохните, затем выдохните и подайте корпус назад. \n\nПостарайтесь сделать так, чтобы ягодицы касались пяток.Расслабьте локти, коснитесь лбом пола и постарайтесь опустить грудь к полу. Оставайтесь в этом положении.", imageBig: UIImage(named: "ChildPose"), imageSmall: UIImage(named: "yoga-pose"))
    ])
    // Lesson(name: "", time: <#T##Int?#>, counts: <#T##Int?#>, text: "", imageBig: UIImage(named: ""), iamgeSmall: UIImage(named: ""))
}

extension Workouts {
    // MARK: - Пресс продолжающий.
    static let continuingAbs = Workouts(type: .continuing, image: UIImage(named: "ContinuingAbs"), girlImage: UIImage(named: "пресс2"), name: "Пресс", lessons: [
 Lesson(name: "Прыжки", time: 30, counts: nil, text: "Ноги вместе, руки вдоль корпуса. Прыжком разведите ноги, одновременно поднимаю руки в стороны до положения над головой. Прыжком верните в исходное положение. \n\nПовторите нужное количество раз. \n\nУпражнение нагружает все крупные группы мышц, укрепляя все тело.", imageBig: UIImage(named: "Jumping"), imageSmall: UIImage(named: "Прыжки")),
        Lesson(name: "Боковые наклоны к стопам", time: nil, counts: 26, text: "Ложитесь на спину, ноги согните в коленях, руки лежат вдоль корпуса.\n\nПриподнимите корпус от пола и поочередно касайтесь пятки пальцами той же руки.", imageBig: UIImage(named: "SideBendsTheFeet"), imageSmall: UIImage(named: "icons8-sit-ups-96")),
        Lesson(name: "Скручивания с поворотом", time: nil, counts: 20, text: "Ложитесь на спину, колени согнуты, руки за головой. \n\nПоднимайте и скручивайте корпус так, чтобы коснуться  правым локтем левого колена. Повторите в другую сторону.", imageBig: UIImage(named: "TwistsTurns"), imageSmall: UIImage(named: "Скручивания с поворотом")),
        Lesson(name: "Альпинист", time: nil, counts: 20, text: "Примите упор лежа. Подтяните правое колено к груди, выпрыгните и поменяйте в воздухе ноги – левую вперед, правую назад.\n\nУкрепляет многие группы мышц, полезно для сердечно-сосудистой системы.", imageBig: UIImage(named: "Mountaineer"), imageSmall: UIImage(named: "Альпинист")),
        Lesson(name: "Боковой мостик (влево)", time: nil, counts: 12, text: "Ложитесь на правый бок. Поставьте правый локоть прямо под плечо, положите левую руку на талию. Левую ногу положите на правую. \n\nПоднимите бедра, останьтесь в этом положении 2-4 секунды, вернитесь в исходное положение.Повторите упражнение.", imageBig: UIImage(named: "lateral(left)"), imageSmall: UIImage(named: "plank")),
        Lesson(name: "Боковой мостик (вправо)", time: nil, counts: 12, text: "Ложитесь на левый бок. Поставьте левый локоть прямо под плечо, положите правую руку на талию. Правую ногу положите на левую. \n\nПоднимите бедра, останьтесь в этом положении 2-4 секунды, вернитесь в исходное ", imageBig: UIImage(named: "SideM Bridge(to the right)"), imageSmall: UIImage(named: "plank")),
        Lesson(name: "Ягодичный мостик", time: nil, counts: 20, text: "И.п. лежа на спине. Согните ноги в коленях, ступни на полу, руки  ладонями вниз вдоль тела. \n\nКак можно выше поднимите таз, сделав мостик.", imageBig: UIImage(named: "GluteusMostik"), imageSmall: UIImage(named: "Ягодичный мостик")),
        Lesson(name: "Велосипед", time: nil, counts: 20, text: "Лягте на спину, положите руки под голову, поднимите колени и крутите «педали велосипеда». \n\nЗатем начните делать наклоны вперед, касаясь локтями противоположного колена.", imageBig: UIImage(named: "Bicycle"), imageSmall: UIImage(named: "workout-5")),
        Lesson(name: "Уголок", time: nil, counts: 20, text: "Ложитесь на спину, руки и ноги вытянуты, ноги вместе. \n\nПоднимите корпус и ноги, коснитесь руками носков. Вернитесь в исходное положение и повторите упражнение.", imageBig: UIImage(named: "Corner"), imageSmall: UIImage(named: "Качели")),
        Lesson(name: "Боковые наклоны к стопам", time: nil, counts: 26, text: "Ложитесь на спину, ноги согните в коленях, руки лежат вдоль корпуса. \n\nПриподнимите корпус от пола и поочередно касайтесь пятки пальцами той же руки.", imageBig: UIImage(named: "SideBendsTheFeet"), imageSmall: UIImage(named: "icons8-sit-ups-96")),
        Lesson(name: "Упражнения для пресса", time: nil, counts: 20, text: "Лягте на спину, ноги согнуты в коленях. Приподнимаем корпус. \n\nЗадержитесь в верхнем положении на несколько секунд и медленно вернитесь в исходное положение. \n\nОсновная нагрузка приходится на прямую и косые мышцы живота.", imageBig: UIImage(named: "ExercisesForTheAbs"), imageSmall: UIImage(named: "Упражнения для пресса")),
        Lesson(name: "Планка", time: 30, counts: nil, text: "Удерживайте положение «упор лежа» на локтях и пальцах ног. \n\nПытайтесь сохранить это положение с прямой спиной.Упражнение укрепляет мышцы живота, спины и плеч.", imageBig: UIImage(named: "Plank"), imageSmall: UIImage(named: "Планка")),
        Lesson(name: "Скручивания с поворотом", time: nil, counts: 20, text: "Ложитесь на спину, колени согнуты, руки за головой. \n\nПоднимайте и скручивайте корпус так, чтобы коснуться  правым локтем левого колена. Повторите в другую сторону.", imageBig: UIImage(named: "TwistsTurns"), imageSmall: UIImage(named: "Скручивания с поворотом")),
        Lesson(name: "Поднятие ног лежа на спине", time: nil, counts: 16, text: "Лягте на спину и положите руки под бедра для поддержки. \n\nПоднимите прямые ноги вверх до образования прямого угла с полом.Медленно опустите ноги вниз и повторите упражнение.", imageBig: UIImage(named: "LegRaisesLyingOnBack"), imageSmall: UIImage(named: "Поднятие ног лежа на спине")),
        Lesson(name: "Велосипед", time: nil, counts: 20, text: "Лягте на спину, положите руки под голову, поднимите колени и крутите «педали велосипеда». \n\nЗатем начните делать наклоны вперед, касаясь локтями противоположного колена.", imageBig: UIImage(named: "Bicycle"), imageSmall: UIImage(named: "workout-5")),
        Lesson(name: "Отжимания с поворотом", time: nil, counts: 20, text: "Примите упор лежа. Выполните отжимание. \n\nПри подъеме в верхнее положение выполните поворот корпуса и вытяните правую руку вверх. Повторите для другой руки. \n\nОтличное упражнение для мышц груди, плечевого пояса, рук и мышц кора", imageBig: UIImage(named: "PushUpsTurns"), imageSmall: UIImage(named: "Отжимания с поворотом")),
        Lesson(name: "Планка с правого бока", time: 20, counts: nil, text: "Лягте на бок с упором на локоть, бедра оторваны от пола, удерживайте тело прямо от головы до ног. \n\nЭто упражнение для мышц пресса, прежде всего, для косой.", imageBig: UIImage(named: "RightSidePlank"), imageSmall: UIImage(named: "plank")),
        Lesson(name: "Планка с левого бока", time: 20, counts: nil, text: "Лягте на бок с упором на локоть, бедра оторваны от пола, удерживайте тело прямо от головы до ног. \n\nЭто упражнение для мышц пресса, прежде всего, для косой.", imageBig: UIImage(named: "PlankFromLeftSide"), imageSmall: UIImage(named: "plank")),
        Lesson(name: "Растяжка «кобра»", time: 20, counts: nil, text: "Ложитесь на живот. Руки согнуты в локтях, ладони на полу под плечами. \n\nПоднимите грудь как можно выше над полом. Оставайтесь в этом положении несколько секунд", imageBig: UIImage(named: "CobraStretch"), imageSmall: UIImage(named: "Растяжка «кобра»")),
        Lesson(name: "Скручивания в пояснице лежа на полу (влево)", time: 30, counts: nil, text: "Ложитесь на спину, ноги вытянуты. \n\nПоднимите левую ногу и потяните ее за колено правой рукой в правую сторону. \n\nОставайтесь в этом положении несколько секунд.", imageBig: UIImage(named: "LumbarCurlsLyingOnTheFloor (toTheLeft)"), imageSmall: UIImage(named: "Скручивания в пояснице лежа на полу")),
        Lesson(name: "Скручивания в пояснице лежа на полу (вправо)", time: 30, counts: nil, text: "Ложитесь на спину, ноги вытянуты. \n\nПоднимите правую ногу и потяните ее за колено левой рукой в левую сторону. \n\nОставайтесь в этом положении несколько секунд.", imageBig: UIImage(named: "LumbarCurlsLyingOnTheFloor (toTheRight)"), imageSmall: UIImage(named: "Скручивания в пояснице лежа на полу"))
    ])
    // MARK: - грудь продолжающий.
    ///грудь продолжающий - Chestcontinuing
    static let continuingChest = Workouts(type: .continuing, image: UIImage(named: "continuingChest"), girlImage: UIImage(named: "грудь2"), name: "Грудь", lessons: [
        Lesson(name: "Прыжки", time: 30, counts: nil, text: "Ноги вместе, руки вдоль корпуса. Прыжком разведите ноги, одновременно поднимаю руки в стороны до положения над головой. Прыжком верните в исходное положение. \n\nПовторите нужное количество раз. Упражнение нагружает все крупные группы мышц, укрепляя все тело.", imageBig: UIImage(named: "Jumping"), imageSmall: UIImage(named: "Прыжки")),
        Lesson(name: "Отжимания с упором на колени", time: nil, counts: 12, text: "Исходное положение – обычное положение для отжиманий, но с упором на колени и приподнятыми стопами. Выполняйте отжимания.", imageBig: UIImage(named: "KneeBasedPushUps"), imageSmall: UIImage(named: "Отжимания с упором на колени")),
        Lesson(name: "Отжимания от пола", time: nil, counts: 12, text: "Поднятие и опускание тела с помощью рук, держите тело прямо. \n\nЭто упражнения прорабатывает мышцы груди, плеч, трицепса, спину и ноги.", imageBig: UIImage(named: "FloorPushUps"), imageSmall: UIImage(named: "Отжимания от пола")),
        Lesson(name: "Отжимания с широким упором", time: nil, counts: 16, text: "Исходное положение – обычное положение для отжиманий, но с упором шире плеч. \n\nВыполняйте отжимания. Не забывайте держать корпус прямо.", imageBig: UIImage(named: "PushupsWithWideSupport"), imageSmall: UIImage(named: "Отжимания с широким упором")),
        Lesson(name: "Отжимания по-индийски", time: nil, counts: 10, text: "Исходно положение – руки и ноги касаются пола, бедра подтянуты вверх. Положение напоминает перевернутую букву «V». \n\nСогните руки в локтях, опуская тело к полу. Когда тело будет близко к полу, поднимите корпус как можно выше. \n\nЗатем вернитесь в исходное положение и повторите упражнение.", imageBig: UIImage(named: "IndianStylePushups"), imageSmall: UIImage(named: "Отжимания по-индийски")),
        Lesson(name: "Отжимания с поворотом", time: nil, counts: 10, text: "Примите упор лежа. Выполните отжимание. \n\nПри подъеме в верхнее положение выполните поворот корпуса и вытяните правую руку вверх. Повторите для другой руки. \n\nОтличное упражнение для мышц груди, плечевого пояса, рук и мышц кора.", imageBig: UIImage(named: "PushUpsTurns"), imageSmall: UIImage(named: "Отжимания с поворотом")),
        Lesson(name: "Отжимания с упором на колени", time: nil, counts: 12, text: "Исходное положение – обычное положение для отжиманий, но с упором на колени и приподнятыми стопами. Выполняйте отжимания.", imageBig: UIImage(named: "KneeBasedPushUps"), imageSmall: UIImage(named: "Отжимания с упором на колени")),
        Lesson(name: "Отжимания по-индийски", time: nil, counts: 10, text: "Исходно положение – руки и ноги касаются пола, бедра подтянуты вверх. Положение напоминает перевернутую букву «V». \n\nСогните руки в локтях, опуская тело к полу. Когда тело будет близко к полу, поднимите корпус как можно выше. \n\nЗатем вернитесь в исходное положение и повторите упражнение.", imageBig: UIImage(named: "IndianStylePushups"), imageSmall: UIImage(named: "Отжимания по-индийски")),
        Lesson(name: "Отжимания с упором сзади", time: nil, counts: 12, text: "Исходное положение – на четвереньках, колени под ягодицами, руки под плечами. \n\nПоднимите ноги на стул или скамью и выполняйте отжимания преимущественно силой рук. \n\nНе забывайте держать корпус прямо.", imageBig: UIImage(named: "Push-upsWithBackSupport"), imageSmall: UIImage(named: "Отжимания с упором сзади")),
        Lesson(name: "Растяжка «кобра»", time: 30, counts: nil, text: "Ложитесь на живот. Руки согнуты в локтях, ладони на полу под плечами. \n\nПоднимите грудь как можно выше над полом. Оставайтесь в этом положении несколько секунд", imageBig: UIImage(named: "CobraStretch"), imageSmall: UIImage(named: "Растяжка «кобра»")),
        Lesson(name: "Грудь ", time: 30, counts: nil, text: "Встаньте в дверной проем в положении выпада, положив предплечья по сторонам на дверной косяк, локти чуть ниже плеч. Затем медленно подайте грудь вперед. \n\nОставайтесь в этом положении 20 секунд. Затем медленно отведите грудь назад в исходное положение, опустите руки и сделайте несколько вращательных движений плечами назад.", imageBig: UIImage(named: "Chest"), imageSmall: UIImage(named: "Грудь"))
    ])
    // MARK: - руки продолжающий.
    ///руки продолжающий - armsСontinuing
    static let continuingArms = Workouts(type: .continuing, image: UIImage(named: "continuingArms"), girlImage: UIImage(named: "руки2"), name: "Руки", lessons: [
        Lesson(name: "Махи руками по часовой стрелке ", time: 30, counts: nil, text: "Встаньте ровно, руки вытянуты в стороны на уровне плеч. \n\nБыстро вращайте руками от плеч по часовой стрелке.", imageBig: UIImage(named: "HandSwings"), imageSmall: UIImage(named: "Грудь")),
        Lesson(name: "Махи руками против часовой стрелке ", time: 30, counts: nil, text: "Встаньте ровно, руки вытянуты в стороны на уровне плеч. \n\nБыстро вращайте руками от плеч против  часовой стрелке.", imageBig: UIImage(named: "HandSwings"), imageSmall: UIImage(named: "Грудь")),
        Lesson(name: "Военные отжимания", time: nil, counts: 20, text: "Примите упор лежа, руки ровно под плечами, локти близко к корпусу, расстояние между ступнями не больше 30 сантиметров. \n\nСгибайте руки в локтях и опускайте тело, пока плечевые части рук не будут параллельны полу. Задержитесь в этом положении на одну секунду, затем вернитесь в исходное положение, отжавшись от пола, и повторите упражнение.", imageBig: UIImage(named: "FloorPushUps"), imageSmall: UIImage(named: "Военные отжимания")),
        Lesson(name: "Отжимания с поворотом", time: nil, counts: 12, text: "Примите упор лежа. Выполните отжимание. \n\nПри подъеме в верхнее положение выполните поворот корпуса и вытяните правую руку вверх. Повторите для другой руки. \n\nОтличное упражнение для мышц груди, плечевого пояса, рук и мышц кора.", imageBig: UIImage(named: "PushUpsTurns"), imageSmall: UIImage(named: "Отжимания с поворотом")),
        Lesson(name: "Военные отжимания", time: nil, counts: 20, text: "Примите упор лежа, руки ровно под плечами, локти близко к корпусу, расстояние между ступнями не больше 30 сантиметров. \n\nСгибайте руки в локтях и опускайте тело, пока плечевые части рук не будут параллельны полу. Задержитесь в этом положении на одну секунду, затем вернитесь в исходное положение, отжавшись от пола, и повторите упражнение.", imageBig: UIImage(named: "FloorPushUps"), imageSmall: UIImage(named: "Военные отжимания")),
        Lesson(name: "Отжимания с поворотом", time: nil, counts: 12, text: "Примите упор лежа. Выполните отжимание. \n\nПри подъеме в верхнее положение выполните поворот корпуса и вытяните правую руку вверх. Повторите для другой руки. \n\nОтличное упражнение для мышц груди, плечевого пояса, рук и мышц кора.", imageBig: UIImage(named: "PushUpsTurns"), imageSmall: UIImage(named: "Отжимания с поворотом")),
        Lesson(name: "Отжимания от пола", time: nil, counts: 15, text: "Поднятие и опускание тела с помощью рук, держите тело прямо. \n\nЭто упражнения прорабатывает мышцы груди, плеч, трицепса, спину и ноги.", imageBig: UIImage(named: "FloorPushUps"), imageSmall: UIImage(named: "Отжимания от пола")),
        Lesson(name: "Низкий старт", time: nil, counts: 10, text: "Из положения стоя опуститесь на корточки и упритесь руками в землю. \n\nОдновременно выпрямите руки и ноги и сразу же вернитесь в положение «на корточках».Затем выпрыгните вверх. \n\n«Низкий старт»- это аэробное силовое упражнение для мышц всего тела.", imageBig: UIImage(named: "startLow"), imageSmall: UIImage(named: "Низкий старт")),
        Lesson(name: "Ножницы руками", time: 30, counts: nil, text: "Встаньте ровно, ноги на ширине плеч. \n\nВытяните руки перед собой на уровне плеч, так, чтобы одна была чуть выше другой, а вместе они составляли букву «Х». Затем разведите руки в стороны. \n\nПовторите упражнение так, чтобы теперь выше была другая рука.", imageBig: UIImage(named: "ScissorHands"), imageSmall: UIImage(named: "exercise-4")),
        Lesson(name: "Отжимания от пола", time: nil, counts: 15, text: "Поднятие и опускание тела с помощью рук, держите тело прямо. \n\nЭто упражнения прорабатывает мышцы груди, плеч, трицепса, спину и ноги.", imageBig: UIImage(named: "FloorPushUps"), imageSmall: UIImage(named: "Отжимания от пола")),
        Lesson(name: "Низкий старт", time: nil, counts: 10, text: "Из положения стоя опуститесь на корточки и упритесь руками в землю. \n\nОдновременно выпрямите руки и ноги и сразу же вернитесь в положение «на корточках».Затем выпрыгните вверх. \n\n«Низкий старт»- это аэробное силовое упражнение для мышц всего тела.", imageBig: UIImage(named: "startLow"), imageSmall: UIImage(named: "Низкий старт")),
        Lesson(name: "Гусеница", time: nil, counts: 12, text: "Ноги на ширине плеч. Согните корпус и идите на руках вперед так далеко, как сможете, затем вернитесь на руках обратно. Повторите упражнения.", imageBig: UIImage(named: "Caterpillar"), imageSmall: UIImage(named: "icons8-приседания"))
    ])
    // MARK: - Ноги продолжающий.
    ///Ноги продолжающий - continuationLegs
    static let continuationLegs = Workouts(type: .continuing, image: UIImage(named: "continuationLegs"), girlImage: UIImage(named: "ноги2"), name: "Ноги", lessons: [
        Lesson(name: "Прыжки", time: 30, counts: nil, text: "Ноги вместе, руки вдоль корпуса. Прыжком разведите ноги, одновременно поднимаю руки в стороны до положения над головой. Прыжком верните в исходное положение. \n\nПовторите нужное количество раз. Упражнение нагружает все крупные группы мышц, укрепляя все тело.", imageBig: UIImage(named: "Jumping"), imageSmall: UIImage(named: "Прыжки")),
        Lesson(name: "Приседания", time: nil, counts: 12, text: "Ноги на ширине плеч, руки вытянуты перед собой. Опускайтесь до тех пор, пока бедра не будут паралельны полу. \n\nПри выполнении упражнения колени должны быть направлены туда же, куда направлены носки ног. Вернитесь в исходное положение.Повторите нужное количество раз. \n\nУпражнение нагружает мышцы передней и задней поверхности бедра, ягодицы, нижней части корпуса.", imageBig: UIImage(named: "Squats"), imageSmall: UIImage(named: "Приседания")),
        Lesson(name: "Приседания", time: nil, counts: 12, text: "Ноги на ширине плеч, руки вытянуты перед собой. Опускайтесь до тех пор, пока бедра не будут паралельны полу. \n\nПри выполнении упражнения колени должны быть направлены туда же, куда направлены носки ног. Вернитесь в исходное положение.Повторите нужное количество раз. \n\nУпражнение нагружает мышцы передней и задней поверхности бедра, ягодицы, нижней части корпуса.", imageBig: UIImage(named: "Squats"), imageSmall: UIImage(named: "Приседания")),
        Lesson(name: "Приседания", time: nil, counts: 12, text: "Ноги на ширине плеч, руки вытянуты перед собой. Опускайтесь до тех пор, пока бедра не будут паралельны полу. \n\nПри выполнении упражнения колени должны быть направлены туда же, куда направлены носки ног. Вернитесь в исходное положение.Повторите нужное количество раз. \n\nУпражнение нагружает мышцы передней и задней поверхности бедра, ягодицы, нижней части корпуса.", imageBig: UIImage(named: "Squats"), imageSmall: UIImage(named: "Приседания")),
        Lesson(name: "Пожарный кран влево", time: nil, counts: 12, text: "И.п. стоя на четвереньках, колени строго под бедрами, руки под плечами. \n\nПоднимите пятку левой ноги к ягодице и как можно дальше вытяните колено в сторону.", imageBig: UIImage(named: "fireHydrantLeft"), imageSmall: UIImage(named: "Диагональная «планка»")),
        Lesson(name: "Пожарный кран вправо", time: nil, counts: 12, text: "И.п. стоя на четвереньках, колени строго под бедрами, руки под плечами. \n\nПоднимите пятку правой ноги к ягодице и как можно дальше вытяните колено в сторону.", imageBig: UIImage(named: "fireHydrantright"), imageSmall: UIImage(named: "Диагональная «планка»")),
        Lesson(name: "Пожарный кран влево", time: nil, counts: 12, text: "И.п. стоя на четвереньках, колени строго под бедрами, руки под плечами. \n\nПоднимите пятку левой ноги к ягодице и как можно дальше вытяните колено в сторону.", imageBig: UIImage(named: "fireHydrantLeft"), imageSmall: UIImage(named: "Диагональная «планка»")),
        Lesson(name: "Пожарный кран вправо", time: nil, counts: 12, text: "И.п. стоя на четвереньках, колени строго под бедрами, руки под плечами. \n\nПоднимите пятку правой ноги к ягодице и как можно дальше вытяните колено в сторону.", imageBig: UIImage(named: "fireHydrantright"), imageSmall: UIImage(named: "Диагональная «планка»")),
        Lesson(name: "Пожарный кран влево", time: nil, counts: 12, text: "И.п. стоя на четвереньках, колени строго под бедрами, руки под плечами. \n\nПоднимите пятку левой ноги к ягодице и как можно дальше вытяните колено в сторону.", imageBig: UIImage(named: "fireHydrantLeft"), imageSmall: UIImage(named: "Диагональная «планка»")),
        Lesson(name: "Пожарный кран вправо", time: nil, counts: 12, text: "И.п. стоя на четвереньках, колени строго под бедрами, руки под плечами. \n\nПоднимите пятку правой ноги к ягодице и как можно дальше вытяните колено в сторону.", imageBig: UIImage(named: "fireHydrantright"), imageSmall: UIImage(named: "Диагональная «планка»")),
        Lesson(name: "Выпад назад", time: nil, counts: 14, text: "Встаньте ровно, ноги на ширине плеч, руки на бедрах. \n\nСделайте большой шаг назад правой ногой, опускаясь всем телом так, чтобы левое бедро было параллельно полу. в исходное положение и повторите упражнения в другую сторону.", imageBig: UIImage(named: "BackLunge"), imageSmall: UIImage(named: "icons8-stretching-96")),
        Lesson(name: "Выпад назад", time: nil, counts: 14, text: "Встаньте ровно, ноги на ширине плеч, руки на бедрах. \n\nСделайте большой шаг назад правой ногой, опускаясь всем телом так, чтобы левое бедро было параллельно полу. в исходное положение и повторите упражнения в другую сторону.", imageBig: UIImage(named: "BackLunge"), imageSmall: UIImage(named: "icons8-stretching-96")),
        Lesson(name: "Круги лежа на боку левую", time: nil, counts: 12, text: "Лёжа на правом боку, поднимите вверх левую ногу и вращайте кругами.", imageBig: UIImage(named: "sideLuvyCircles"), imageSmall: UIImage(named: "plank")),
        Lesson(name: "Круги лежа на боку правую", time: nil, counts: 12, text: "Лёжа на левом боку, поднимите вверх правую ногу и вращайте кругами.", imageBig: UIImage(named: "lateralRightCircles"), imageSmall: UIImage(named: "plank")),
        Lesson(name: "Круги лежа на боку левую", time: nil, counts: 12, text: "Лёжа на правом боку, поднимите вверх левую ногу и вращайте кругами.", imageBig: UIImage(named: "sideLuvyCircles"), imageSmall: UIImage(named: "plank")),
        Lesson(name: "Круги лежа на боку правую", time: nil, counts: 12, text: "Лёжа на левом боку, поднимите вверх правую ногу и вращайте кругами.", imageBig: UIImage(named: "lateralRightCircles"), imageSmall: UIImage(named: "plank")),
        Lesson(name: "Сумо-приседания", time: nil, counts: 12, text: "Встаньте ровно, ноги на ширине 15-30 сантиметров. \n\nОпускайтесь до тех пор, пока бедра не станут параллельны полу. Вернитесь в исходное положение и повторите упражнение.", imageBig: UIImage(named: "squatsSumo"), imageSmall: UIImage(named: "Сумо-приседания")),
        Lesson(name: "Сумо-приседания", time: nil, counts: 12, text: "Встаньте ровно, ноги на ширине 15-30 сантиметров. \n\nОпускайтесь до тех пор, пока бедра не станут параллельны полу. Вернитесь в исходное положение и повторите упражнение.", imageBig: UIImage(named: "squatsSumo"), imageSmall: UIImage(named: "Сумо-приседания")),
        Lesson(name: "Сумо-приседания", time: nil, counts: 12, text: "Встаньте ровно, ноги на ширине 15-30 сантиметров. \n\nОпускайтесь до тех пор, пока бедра не станут параллельны полу. Вернитесь в исходное положение и повторите упражнение.", imageBig: UIImage(named: "squatsSumo"), imageSmall: UIImage(named: "Сумо-приседания")),
        Lesson(name: "Растяжка четырехглавой мышцы у стены (левая нога)", time: 30, counts: nil, text: "Встаньте ровно, правая рука на стене. Согните левую ногу в колене и обхватите щиколотку или ступню левой рукой. Подтяните левую голень к левому бедру. Оставайтесь в этом положении.", imageBig: UIImage(named: "Stretch(left leg)"), imageSmall: UIImage(named: "Растяжка четырехглавой")),
        Lesson(name: "Растяжка четырехглавой мышцы у стены (правая нога)", time: 30, counts: nil, text: "Встаньте ровно, левая рука на стене. Согните правую ногу в колене и обхватите щиколотку или ступню правой  рукой. Подтяните правую голень к правому бедру. Оставайтесь в этом положении.", imageBig: UIImage(named: "Stretch(right leg)"), imageSmall: UIImage(named: "Растяжка четырехглавой")),
        Lesson(name: "Растяжка «левое колено к груди»", time: 30, counts: nil, text: "Ложитесь спиной на пол, ноги вытянуты. Поднимите левое колено и схватите его обеими руками. \n\nПотяните левое колено как можно ближе к груди, прямая правая нога при этом должна лежать на полу. \n\nОставайтесь в этом положении несколько секунд.", imageBig: UIImage(named: "LeftKneeToChestStretch"), imageSmall: UIImage(named: "workout-5")),
        Lesson(name: "Растяжка «правое колено к груди»", time: 30, counts: nil, text: "Ложитесь спиной на пол, ноги вытянуты. Поднимите правое колено и схватите его обеими руками. \n\nПотяните правое колено как можно ближе к груди, прямая левая нога при этом должна лежать на полу. \n\nОставайтесь в этом положении несколько секунд.", imageBig: UIImage(named: "RightKneeToChestStretch"), imageSmall: UIImage(named: "workout-5"))
    ])
    // MARK: - Плечи и спина продолжающий.
    ///Плечи и спина продолжающий - continuingShouldersAndBack 
    static let continuingShouldersAndBack  = Workouts(type: .continuing, image: UIImage(named: "continuingShouldersAndBack"), girlImage: UIImage(named: "спина2"), name: "Плечи и спина", lessons: [
        Lesson(name: "Прыжки", time: 30, counts: nil, text: "Ноги вместе, руки вдоль корпуса. Прыжком разведите ноги, одновременно поднимаю руки в стороны до положения над головой. Прыжком верните в исходное положение. \n\nПовторите нужное количество раз. Упражнение нагружает все крупные группы мышц, укрепляя все тело.", imageBig: UIImage(named: "Jumping"), imageSmall: UIImage(named: "Прыжки")),
        Lesson(name: "Отжимания с опорой впереди", time: nil, counts: 16, text: "Исходное положение – обычное положение для отжиманий, но с руками на стуле или скамье. \n\nВыполняйте отжимания силой рук. Не забывайте держать корпус прямо.", imageBig: UIImage(named: "FrontPushUp"), imageSmall: UIImage(named: "Отжимания с опорой впереди")),
        Lesson(name: "Поза кошки", time: 30, counts: nil, text: "Начальное положение – на четвереньках, колени под ягодицами, ладони прямо под плечами. \n\nДелая вдох, опустите живот, разверните плечи и поднимите голову. \n\nДелая выдох, выгните спину наверх и опустите голову. Повторите упражнение.", imageBig: UIImage(named: "CatPose"), imageSmall: UIImage(named: "yoga-pose-2")),
        Lesson(name: "Отжимания с опорой впереди", time: nil, counts: 16, text: "Исходное положение – обычное положение для отжиманий, но с руками на стуле или скамье. \n\nВыполняйте отжимания силой рук. Не забывайте держать корпус прямо.", imageBig: UIImage(named: "FrontPushUp"), imageSmall: UIImage(named: "Отжимания с опорой впереди")),
        Lesson(name: "Наклоны вперед", time: nil, counts: 10, text: "Встаньте ровно, ноги на ширине плеч. \n\nПодайте бедра назад и наклоните прямой корпус вперед. Медленно вернитесь в исходное положение, повторите упражнение.", imageBig: UIImage(named: "forwardLeans"), imageSmall: UIImage(named: "Наклоны вперед")),
        Lesson(name: "Отжимания со смещением", time: nil, counts: 14, text: "Примите упор лежа. Опуститесь на руках. В нижней точке переместите корпус влево, затем вправо. \n\nПоднимитесь на руках. Повторите упражнение.", imageBig: UIImage(named: "Push-upsWithOffset"), imageSmall: UIImage(named: "Отжимания от пола")),
        Lesson(name: "Отжимания со смещением", time: nil, counts: 12, text: "Примите упор лежа. Опуститесь на руках. В нижней точке переместите корпус влево, затем вправо. \n\nПоднимитесь на руках. Повторите упражнение.", imageBig: UIImage(named: "Push-upsWithOffset"), imageSmall: UIImage(named: "Отжимания от пола")),
        Lesson(name: "Отжимания со смещением", time: nil, counts: 10, text: "Примите упор лежа. Опуститесь на руках. В нижней точке переместите корпус влево, затем вправо. \n\nПоднимитесь на руках. Повторите упражнение.", imageBig: UIImage(named: "Push-upsWithOffset"), imageSmall: UIImage(named: "Отжимания от пола")),
        Lesson(name: "Отжимания со смещением", time: nil, counts: 8, text: "Примите упор лежа. Опуститесь на руках. В нижней точке переместите корпус влево, затем вправо. \n\nПоднимитесь на руках. Повторите упражнение.", imageBig: UIImage(named: "Push-upsWithOffset"), imageSmall: UIImage(named: "Отжимания от пола")),
        Lesson(name: "Поза ребенка", time: 30, counts: nil, text: "Начальное положение – с коленями и ладонями на полу. \n\nСлегка вытяните руки вперед, раздвиньте колени и сведите вместе ступни. Вдохните, затем выдохните и подайте корпус назад. Постарайтесь сделать так, чтобы ягодицы касались пяток. \n\nРасслабьте локти, коснитесь лбом пола и постарайтесь опустить грудь к полу. Оставайтесь в этом положении.", imageBig: UIImage(named: "ChildPose"), imageSmall: UIImage(named: "yoga-pose"))
        
    ])
}

// MARK: - Продвинутый.
extension Workouts {
    // MARK: - Пресс продвинутый.
    ///пресс продвинутый - advancedAbc
    static let advancedAbs = Workouts(type: .advanced, image: UIImage(named: "advancedAbs"), girlImage: UIImage(named: "пресс3"), name: "Пресс", lessons: [
        Lesson(name: "Прыжки", time: 30, counts: nil, text: "Ноги вместе, руки вдоль корпуса. Прыжком разведите ноги, одновременно поднимаю руки в стороны до положения над головой. Прыжком верните в исходное положение. \n\nПовторите нужное количество раз. Упражнение нагружает все крупные группы мышц, укрепляя все тело.", imageBig: UIImage(named: "Jumping"), imageSmall: UIImage(named: "Прыжки")),
        Lesson(name: "Упражнения для пресса", time: nil, counts: 20, text: "Лягте на спину, ноги согнуты в коленях. Приподнимаем корпус. \n\nЗадержитесь в верхнем положении на несколько секунд и медленно вернитесь в исходное положение. \n\nОсновная нагрузка приходится на прямую и косые мышцы живота.", imageBig: UIImage(named: "ExercisesForTheAbs"), imageSmall: UIImage(named: "Упражнения для пресса")),
        //SideM Bridge(to the righ - SideM Bridge(to the righ)
        Lesson(name: "Боковой мостик (вправо)", time: nil, counts: 20, text: "Ложитесь на левый бок. Поставьте левый локоть прямо под плечо, положите правую руку на талию. Правую ногу положите на левую. \n\nПоднимите бедра, останьтесь в этом положении 2-4 секунды, вернитесь в исходное положение. \n\nПовторите упражнение.", imageBig: UIImage(named: "SideM Bridge(no the tright)"), imageSmall: UIImage(named: "plank")),
        Lesson(name: "Боковой мостик (влево)", time: nil, counts: 20, text: "Ложитесь на правый бок. Поставьте правый локоть прямо под плечо, положите левую руку на талию. Левую ногу положите на правую. \n\nПоднимите бедра, останьтесь в этом положении 2-4 секунды, вернитесь в исходное положение. \n\nПовторите упражнение.", imageBig: UIImage(named: "lateral(left)"), imageSmall: UIImage(named: "plank")),
        Lesson(name: "Упражнения для пресса", time: nil, counts: 30, text: "Лягте на спину, ноги согнуты в коленях. Приподнимаем корпус. \n\nЗадержитесь в верхнем положении на несколько секунд и медленно вернитесь в исходное положение. \n\nОсновная нагрузка приходится на прямую и косые мышцы живота.", imageBig: UIImage(named: "ExercisesForTheAbs"), imageSmall: UIImage(named: "Упражнения для пресса")),
        Lesson(name: "Велосипед", time: nil, counts: 24, text: "Лягте на спину, положите руки под голову, поднимите колени и крутите «педали велосипеда». \n\nЗатем начните делать наклоны вперед, касаясь локтями противоположного колена.", imageBig: UIImage(named: "Bicycle"), imageSmall: UIImage(named: "workout-5")),
        Lesson(name: "Планка с правого бока", time: 20, counts: nil, text: "Лягте на бок с упором на локоть, бедра оторваны от пола, удерживайте тело прямо от головы до ног. \n\nЭто упражнение для мышц пресса, прежде всего, для косой.", imageBig: UIImage(named: "RightSidePlank"), imageSmall: UIImage(named: "plank")),
        Lesson(name: "Планка с левого бока", time: 20, counts: nil, text: "Лягте на бок с упором на локоть, бедра оторваны от пола, удерживайте тело прямо от головы до ног. \n\nЭто упражнение для мышц пресса, прежде всего, для косой.", imageBig: UIImage(named: "PlankFromLeftSide"), imageSmall: UIImage(named: "plank")),
        Lesson(name: "Уголок", time: nil, counts: 20, text: "Ложитесь на спину, руки и ноги вытянуты, ноги вместе. \n\nПоднимите корпус и ноги, коснитесь руками носков. Вернитесь в исходное положение и повторите упражнение.", imageBig: UIImage(named: "Corner"), imageSmall: UIImage(named: "Качели")),
        Lesson(name: "Отжимания с поворотом", time: nil, counts: 24, text: "Примите упор лежа. Выполните отжимание. \n\nПри подъеме в верхнее положение выполните поворот корпуса и вытяните правую руку вверх. Повторите для другой руки. \n\nОтличное упражнение для мышц груди, плечевого пояса, рук и мышц кора.", imageBig: UIImage(named: "PushUpsTurns"), imageSmall: UIImage(named: "Отжимания с поворотом")),
        Lesson(name: "Качели", time: nil, counts: 48, text: "Сядьте на пол, согните колени. Ноги слегка приподнять, корпус отклонить назад. \n\nСоедините руки перед грудью и делайте повороты корпуса из стороны в сторону.", imageBig: UIImage(named: "Swing"), imageSmall: UIImage(named: "Качели")),
        Lesson(name: "Упражнения для пресса", time: nil, counts: 30, text: "Лягте на спину, ноги согнуты в коленях. Приподнимаем корпус. \n\nЗадержитесь в верхнем положении на несколько секунд и медленно вернитесь в исходное положение. \n\nОсновная нагрузка приходится на прямую и косые мышцы живота.", imageBig: UIImage(named: "ExercisesForTheAbs"), imageSmall: UIImage(named: "Упражнения для пресса")),
        Lesson(name: "Ягодичный мостик ", time: nil, counts: 30, text: "И.п. лежа на спине. Согните ноги в коленях, ступни на полу, руки  ладонями вниз вдоль тела. \n\nКак можно выше поднимите таз, сделав мостик.", imageBig: UIImage(named: "GluteusMostik"), imageSmall: UIImage(named: "Ягодичный мостик")),
        Lesson(name: "Боковые наклоны к стопам", time: nil, counts: 26, text: "Ложитесь на спину, ноги согните в коленях, руки лежат вдоль корпуса. \n\nПриподнимите корпус от пола и поочередно касайтесь пятки пальцами той же руки.", imageBig: UIImage(named: "SideBendsTheFeet"), imageSmall: UIImage(named: "icons8-sit-ups-96")),
        Lesson(name: "Альпинист", time: nil, counts: 30, text: "Примите упор лежа. Подтяните правое колено к груди, выпрыгните и поменяйте в воздухе ноги – левую вперед, правую назад. \n\nУкрепляет многие группы мышц, полезно для сердечно-сосудистой системы.", imageBig: UIImage(named: "Mountaineer"), imageSmall: UIImage(named: "Альпинист")),
        Lesson(name: "Скручивания с поворотом ", time: nil, counts: 24, text: "Ложитесь на спину, колени согнуты, руки за головой. \n\nПоднимайте и скручивайте корпус так, чтобы коснуться  правым локтем левого колена. Повторите в другую сторону.", imageBig: UIImage(named: "TwistsTurns"), imageSmall: UIImage(named: "Скручивания с поворотом")),
        Lesson(name: "Уголок", time: nil, counts: 16, text: "Ложитесь на спину, руки и ноги вытянуты, ноги вместе. \n\nПоднимите корпус и ноги, коснитесь руками носков. Вернитесь в исходное положение и повторите упражнение.", imageBig: UIImage(named: "Corner"), imageSmall: UIImage(named: "Качели")),
        Lesson(name: "Планка", time: 60, counts: nil, text: "Удерживайте положение «упор лежа» на локтях и пальцах ног. \n\nПытайтесь сохранить это положение с прямой спиной. \n\nУпражнение укрепляет мышцы живота, спины и плеч.", imageBig: UIImage(named: "Plank"), imageSmall: UIImage(named: "Планка")),
        Lesson(name: "Растяжка «кобра»", time: 30, counts: nil, text: "Ложитесь на живот. Руки согнуты в локтях, ладони на полу под плечами. \n\nПоднимите грудь как можно выше над полом. \n\n Оставайтесь в этом положении несколько секунд", imageBig: UIImage(named: "CobraStretch"), imageSmall: UIImage(named: "Растяжка «кобра»")),
        Lesson(name: "Скручивания в пояснице лежа на полу (влево)", time: 30, counts: nil, text: "Ложитесь на спину, ноги вытянуты. \n\nПоднимите левую ногу и потяните ее за колено правой рукой в правую сторону. \n\nОставайтесь в этом положении несколько секунд.", imageBig: UIImage(named: "LumbarCurlsLyingOnTheFloor (toTheLeft)"), imageSmall: UIImage(named: "Скручивания в пояснице лежа на полу")),
        Lesson(name: "Скручивания в пояснице лежа на полу (вправо)", time: 30, counts: nil, text: "Ложитесь на спину, ноги вытянуты. \n\nПоднимите правую ногу и потяните ее за колено левой рукой в левую сторону. \n\nОставайтесь в этом положении несколько секунд.", imageBig: UIImage(named: "LumbarCurlsLyingOnTheFloor (toTheRight)"), imageSmall: UIImage(named: "Скручивания в пояснице лежа на полу"))
        
    ])
    // MARK: - Грудь продвинутый.
    ///Грудь продвинутый- advancedChest
    static let advancedChest  = Workouts(type: .advanced, image: UIImage(named: "advancedChest"), girlImage: UIImage(named: "грудь3"), name: "Грудь", lessons: [
        Lesson(name: "Прыжки", time: 30, counts: nil, text: "Ноги вместе, руки вдоль корпуса. Прыжком разведите ноги, одновременно поднимаю руки в стороны до положения над головой. Прыжком верните в исходное положение. \n\nПовторите нужное количество раз. Упражнение нагружает все крупные группы мышц, укрепляя все тело.", imageBig: UIImage(named: "Jumping"), imageSmall: UIImage(named: "Прыжки")),
        Lesson(name: "Вращение руками", time: 30, counts: nil, text: "Встаньте на пол, вытянув прямые руки вперед на высоте плеч.\n руки нал головой, затем вернитесь в исходное положение. Повторите упражнение.", imageBig: UIImage(named: "RotationOfTheArms"), imageSmall: UIImage(named: "icons8-йога-96 1")),
        Lesson(name: "Низкий старт", time: nil, counts: 10, text: "Из положения стоя опуститесь на корточки и упритесь руками в землю. /n/nОдновременно выпрямите руки и ноги и сразу же вернитесь в положение «на корточках».Затем выпрыгните вверх. \n\n«Низкий старт»- это аэробное силовое упражнение для мышц всего тела.", imageBig: UIImage(named: "startLow"), imageSmall: UIImage(named: "Низкий старт")),
        Lesson(name: "Отжимания по-индийски", time: nil, counts: 16, text: "Исходно положение – руки и ноги касаются пола, бедра подтянуты вверх. Положение напоминает перевернутую букву «V». \n\nСогните руки в локтях, опуская тело к полу. Когда тело будет близко к полу, поднимите корпус как можно выше. \n\nЗатем вернитесь в исходное положение и повторите упражнение.", imageBig: UIImage(named: "IndianStylePushups"), imageSmall: UIImage(named: "Отжимания по-индийски")),
        Lesson(name: "Отжимания с поворотом", time: nil, counts: 12, text: "Примите упор лежа. Выполните отжимание. \n\nПри подъеме в верхнее положение выполните поворот корпуса и вытяните правую руку вверх. Повторите для другой руки. \n\nОтличное упражнение для мышц груди, плечевого пояса, рук и мышц кора.", imageBig: UIImage(named: "PushUpsTurns"), imageSmall: UIImage(named: "Отжимания с поворотом")),
        Lesson(name: "Отжимания со сведенными ладонями", time: nil, counts: 16, text: "Примите упор лежа, как при отжимания. \n\nСоедините большие и указательные пальцы рук под грудью в форме алмаза и выполните отжимания.Не забывайте держать корпус прямо.", imageBig: UIImage(named: "Push-upsWithPalmsTogether"), imageSmall: UIImage(named: "Отжимания с опорой впереди")),
        Lesson(name: "Отжимания по-индийски", time: nil, counts: 12, text: "Исходно положение – руки и ноги касаются пола, бедра подтянуты вверх. Положение напоминает перевернутую букву «V». \n\nСогните руки в локтях, опуская тело к полу. Когда тело будет близко к полу, поднимите корпус как можно выше. \n\nЗатем вернитесь в исходное положение и повторите упражнение.", imageBig: UIImage(named: "IndianStylePushups"), imageSmall: UIImage(named: "Отжимания по-индийски")),
        Lesson(name: "Отжимания в позе Спайдермена", time: nil, counts: 20, text: "Исходное положение – обычное положение для отжиманий. Опуская корпус, согните и поднимите одну ногу к боку. \n\nВернитесь в исходное положение и выполните упражнение на другую сторону. \n\nНе забывайте держать корпус прямо.", imageBig: UIImage(named: "positionSpiderman "), imageSmall: UIImage(named: "Отжимания в позе Спайдермена")),
        Lesson(name: "Отжимания с упором сзади", time: nil, counts: 12, text: "Исходное положение – на четвереньках, колени под ягодицами, руки под плечами. \n\nПоднимите ноги на стул или скамью и выполняйте отжимания преимущественно силой рук.Не забывайте держать корпус прямо.", imageBig: UIImage(named: "Push-upsWithBackSupport"), imageSmall: UIImage(named: "Отжимания с упором сзади")),
        Lesson(name: "Отжимания с поворотом", time: nil, counts: 10, text: "Примите упор лежа. Выполните отжимание. \n\nПри подъеме в верхнее положение выполните поворот корпуса и вытяните правую руку вверх. Повторите для другой руки. \n\nОтличное упражнение для мышц груди, плечевого пояса, рук и мышц кора.", imageBig: UIImage(named: "PushUpsTurns"), imageSmall: UIImage(named: "Отжимания с поворотом")),
        Lesson(name: "Растяжка «кобра»", time: 30, counts: nil, text: "Ложитесь на живот. Руки согнуты в локтях, ладони на полу под плечами. \n\nПоднимите грудь как можно выше над полом. Оставайтесь в этом положении несколько секунд", imageBig: UIImage(named: "CobraStretch"), imageSmall: UIImage(named: "Растяжка «кобра»")),
        Lesson(name: "Грудь", time: 30, counts: nil, text: "Встаньте в дверной проем в положении выпада, положив предплечья по сторонам на дверной косяк, локти чуть ниже плеч. Затем медленно подайте грудь вперед. \n\nОставайтесь в этом положении 20 секунд. Затем медленно отведите грудь назад в исходное положение, опустите руки и сделайте несколько вращательных движений плечами назад.", imageBig: UIImage(named: "Chest"), imageSmall: UIImage(named: "Грудь"))
        
        
    ])
    // MARK: - Руки продвинутый.
    ///Руки продвинутый- advancedArms
    static let advancedArms = Workouts(type: .advanced, image: UIImage(named: "advancedArms"), girlImage: UIImage(named: "руки3"), name: "Руки", lessons: [
        Lesson(name: "Махи руками по часовой стрелке ", time: 30, counts: nil, text: "Встаньте ровно, руки вытянуты в стороны на уровне плеч. \n\nБыстро вращайте руками от плеч по часовой стрелке.", imageBig: UIImage(named: "HandSwings"), imageSmall: UIImage(named: "Грудь")),
        Lesson(name: "Махи руками против часовой стрелке ", time: 30, counts: nil, text: "Встаньте ровно, руки вытянуты в стороны на уровне плеч. \n\nБыстро вращайте руками от плеч против  часовой стрелке.", imageBig: UIImage(named: "HandSwings"), imageSmall: UIImage(named: "Грудь")),
        Lesson(name: "Низкий старт", time: nil, counts: 16, text: "Из положения стоя опуститесь на корточки и упритесь руками в землю. \n\nОдновременно выпрямите руки и ноги и сразу же вернитесь в положение «на корточках».Затем выпрыгните вверх. \n\n«Низкий старт»- это аэробное силовое упражнение для мышц всего тела.", imageBig: UIImage(named: "startLow"), imageSmall: UIImage(named: "Низкий старт")),
        Lesson(name: "Военные отжимания", time: nil, counts: 20, text: "Примите упор лежа, руки ровно под плечами, локти близко к корпусу, расстояние между ступнями не больше 30 сантиметров. \n\nСгибайте руки в локтях и опускайте тело, пока плечевые части рук не будут параллельны полу. Задержитесь в этом положении на одну секунду, затем вернитесь в исходное положение, отжавшись от пола, и повторите упражнение.", imageBig: UIImage(named: "pushupsMilitary "), imageSmall: UIImage(named: "Военные отжимания")),
        Lesson(name: "Низкий старт", time: nil, counts: 16, text: "Из положения стоя опуститесь на корточки и упритесь руками в землю. \n\nОдновременно выпрямите руки и ноги и сразу же вернитесь в положение «на корточках».Затем выпрыгните вверх. \n\n«Низкий старт»- это аэробное силовое упражнение для мышц всего тела.", imageBig: UIImage(named: "startLow"), imageSmall: UIImage(named: "Низкий старт")),
        Lesson(name: "Военные отжимания", time: nil, counts: 15, text: "Примите упор лежа, руки ровно под плечами, локти близко к корпусу, расстояние между ступнями не больше 30 сантиметров. \n\nСгибайте руки в локтях и опускайте тело, пока плечевые части рук не будут параллельны полу. Задержитесь в этом положении на одну секунду, затем вернитесь в исходное положение, отжавшись от пола, и повторите упражнение.", imageBig: UIImage(named: "pushupsMilitary "), imageSmall: UIImage(named: "Военные отжимания")),
        Lesson(name: "Отжимания с коленей с задержкой внизу", time: 30, counts: nil, text: "Начните в упоре лежа, ноги на ширине плеч, но колени на полу. \n\nОпускайте корпус, пока локти не будут под углом в 90 градусов. Задержитесь в этом положении.", imageBig: UIImage(named: "KneeBasedPushUps"), imageSmall: UIImage(named: "Отжимания с упором на колени")),
        Lesson(name: "Отжимания с поворотом", time: nil, counts: 12, text: "Примите упор лежа. Выполните отжимание. \n\nПри подъеме в верхнее положение выполните поворот корпуса и вытяните правую руку вверх. Повторите для другой руки. \n\nОтличное упражнение для мышц груди, плечевого пояса, рук и мышц кора.", imageBig: UIImage(named: "PushUpsTurns"), imageSmall: UIImage(named: "Отжимания с поворотом")),
        Lesson(name: "Отжимания с поворотом", time: nil, counts: 10, text: "Примите упор лежа. Выполните отжимание. \n\nПри подъеме в верхнее положение выполните поворот корпуса и вытяните правую руку вверх. Повторите для другой руки. \n\nОтличное упражнение для мышц груди, плечевого пояса, рук и мышц кора.", imageBig: UIImage(named: "PushUpsTurns"), imageSmall: UIImage(named: "Отжимания с поворотом")),
        Lesson(name: "Отжимания с поворотом", time: nil, counts: 18, text: "Примите упор лежа. Выполните отжимание. \n\nПри подъеме в верхнее положение выполните поворот корпуса и вытяните правую руку вверх. Повторите для другой руки. \n\nОтличное упражнение для мышц груди, плечевого пояса, рук и мышц кора.", imageBig: UIImage(named: "PushUpsTurns"), imageSmall: UIImage(named: "Отжимания с поворотом")),
        Lesson(name: "Гусеница", time: nil, counts: 12, text: "Ноги на ширине плеч. Согните корпус и идите на руках вперед так далеко, как сможете, затем вернитесь на руках обратно. Повторите упражнения.", imageBig: UIImage(named: "Caterpillar"), imageSmall: UIImage(named: "icons8-приседания")),
        Lesson(name: "Военные отжимания", time: nil, counts: 10, text: "Примите упор лежа, руки ровно под плечами, локти близко к корпусу, расстояние между ступнями не больше 30 сантиметров. \n\nСгибайте руки в локтях и опускайте тело, пока плечевые части рук не будут параллельны полу. Задержитесь в этом положении на одну секунду, затем вернитесь в исходное положение, отжавшись от пола, и повторите упражнение.", imageBig: UIImage(named: "pushupsMilitary "), imageSmall: UIImage(named: "Военные отжимания")),
        Lesson(name: "Отжимания с коленей с задержкой внизу", time: 30, counts: nil, text: "Начните в упоре лежа, ноги на ширине плеч, но колени на полу. \n\nОпускайте корпус, пока локти не будут под углом в 90 градусов. Задержитесь в этом положении.", imageBig: UIImage(named: "KneeBasedPushUps"), imageSmall: UIImage(named: "Отжимания с упором на колени"))
        
    ])
    // MARK: - Ноги продвинутый.
    ///Ноги продвинутый - advancedLegs
    static let advancedLegs   = Workouts(type: .advanced, image: UIImage(named: "advancedLegs"), girlImage: UIImage(named: "ноги3"), name: "Ноги", lessons: [
        Lesson(name: "Низкий старт", time: nil, counts: 10, text: "Из положения стоя опуститесь на корточки и упритесь руками в землю. \n\nОдновременно выпрямите руки и ноги и сразу же вернитесь в положение «на корточках».Затем выпрыгните вверх. \n\n«Низкий старт»- это аэробное силовое упражнение для мышц всего тела.", imageBig: UIImage(named: "startLow"), imageSmall: UIImage(named: "Низкий старт")),
        Lesson(name: "Приседания", time: nil, counts: 14, text: "Ноги на ширине плеч, руки вытянуты перед собой. Опускайтесь до тех пор, пока бедра не будут паралельны полу. \n\nПри выполнении упражнения колени должны быть направлены туда же, куда направлены носки ног. Вернитесь в исходное положение.Повторите нужное количество раз.  \n\nУпражнение нагружает мышцы передней и задней поверхности бедра, ягодицы, нижней части корпуса.", imageBig: UIImage(named: "Squats"), imageSmall: UIImage(named: "Приседания")),
        Lesson(name: "Приседания", time: nil, counts: 14, text: "Ноги на ширине плеч, руки вытянуты перед собой. Опускайтесь до тех пор, пока бедра не будут паралельны  полу. \n\nПри выполнении упражнения колени должны быть направлены туда же, куда направлены носки ног. Вернитесь в исходное положение.Повторите нужное количество раз. \n\nУпражнение нагружает мышцы передней и задней поверхности бедра, ягодицы, нижней части корпуса.", imageBig: UIImage(named: "Squats"), imageSmall: UIImage(named: "Приседания")),
        Lesson(name: "Приседания", time: nil, counts: 14, text: "Ноги на ширине плеч, руки вытянуты перед собой. Опускайтесь до тех пор, пока бедра не будут параллельны полу. \n\nПри выполнении упражнения колени должны быть направлены туда же, куда направлены носки ног. Вернитесь в исходное положение.Повторите нужное количество раз. \n\nУпражнение нагружает мышцы передней и задней поверхности бедра, ягодицы, нижней части корпуса.", imageBig: UIImage(named: "Squats"), imageSmall: UIImage(named: "Приседания")),
        Lesson(name: "Выпад назад", time: nil, counts: 14, text: "Встаньте ровно, ноги на ширине плеч, руки на бедрах. \n\nСделайте большой шаг назад правой ногой, опускаясь всем телом так, чтобы левое бедро было параллельно полу.  \n\nВернитесь в исходное положение и повторите упражнения в другую сторону.", imageBig: UIImage(named: "BackLunge"), imageSmall: UIImage(named: "icons8-stretching-96")),
        Lesson(name: "Выпад назад", time: nil, counts: 14, text: "Встаньте ровно, ноги на ширине плеч, руки на бедрах. \n\nСделайте большой шаг назад правой ногой, опускаясь всем телом так, чтобы левое бедро было параллельно полу. \n\nВернитесь в исходное положение и повторите упражнения в другую сторону.", imageBig: UIImage(named: "BackLunge"), imageSmall: UIImage(named: "icons8-stretching-96")),
        Lesson(name: "Выпад назад", time: nil, counts: 14, text: "Встаньте ровно, ноги на ширине плеч, руки на бедрах. \n\nСделайте большой шаг назад правой ногой, опускаясь всем телом так, чтобы левое бедро было параллельно полу. \n\nВернитесь в исходное положение и повторите упражнения в другую сторону.", imageBig: UIImage(named: "BackLunge"), imageSmall: UIImage(named: "icons8-stretching-96")),
        Lesson(name: "Круги лежа на боку левую", time: nil, counts: 12, text: "Лёжа на правом боку, поднимите вверх левую ногу и вращайте кругами.", imageBig: UIImage(named: "sideLuvyCircles"), imageSmall: UIImage(named: "plank")),
        Lesson(name: "Круги лежа на боку правую", time: nil, counts: 12, text: "Лёжа на левом боку, поднимите вверх правую ногу и вращайте кругами.", imageBig: UIImage(named: "lateralRightCircles"), imageSmall: UIImage(named: "plank")),
        Lesson(name: "Круги лежа на боку левую", time: nil, counts: 12, text: "Лёжа на правом боку, поднимите вверх левую ногу и вращайте кругами.", imageBig: UIImage(named: "sideLuvyCircles"), imageSmall: UIImage(named: "plank")),
        Lesson(name: "Круги лежа на боку правую", time: nil, counts: 12, text: "Лёжа на левом боку, поднимите вверх правую ногу и вращайте кругами.", imageBig: UIImage(named: "lateralRightCircles"), imageSmall: UIImage(named: "plank")),
        Lesson(name: "Круги лежа на боку левую", time: nil, counts: 12, text: "Лёжа на правом боку, поднимите вверх левую ногу и вращайте кругами.", imageBig: UIImage(named: "sideLuvyCircles"), imageSmall: UIImage(named: "plank")),
        Lesson(name: "Круги лежа на боку правую", time: nil, counts: 12, text: "Лёжа на левом боку, поднимите вверх правую ногу и вращайте кругами.", imageBig: UIImage(named: "lateralRightCircles"), imageSmall: UIImage(named: "plank")),
        Lesson(name: "Прыжки на корточках", time: nil, counts: 14, text: "Присев на корточки, подпрыгните за счет мышц живота. Приземляясь, примите положение «на корточках». \n\nОтличное упражнение для разогрева перед комплексом для пресса.", imageBig: UIImage(named: "squatJumps"), imageSmall: UIImage(named: "Низкий старт")),
        Lesson(name: "Прыжки на корточках", time: nil, counts: 14, text: "Присев на корточки, подпрыгните за счет мышц живота. Приземляясь, примите положение «на корточках». \n\nОтличное упражнение для разогрева перед комплексом для пресса.", imageBig: UIImage(named: "squatJumps"), imageSmall: UIImage(named: "Низкий старт")),
        Lesson(name: "Прыжки на корточках", time: nil, counts: 14, text: "Присев на корточки, подпрыгните за счет мышц живота. Приземляясь, примите положение «на корточках». \n\nОтличное упражнение для разогрева перед комплексом для пресса.", imageBig: UIImage(named: "squatJumps"), imageSmall: UIImage(named: "Низкий старт")),
        Lesson(name: "Сумо-приседания", time: nil, counts: 12, text: "Встаньте ровно, ноги на ширине 15-30 сантиметров. \n\nОпускайтесь до тех пор, пока бедра не станут параллельны полу. Вернитесь в исходное положение и повторите упражнение.", imageBig: UIImage(named: "squatsSumo"), imageSmall: UIImage(named: "Сумо-приседания")),
        Lesson(name: "Сумо-приседания", time: nil, counts: 12, text: "Встаньте ровно, ноги на ширине 15-30 сантиметров. \n\nОпускайтесь до тех пор, пока бедра не станут параллельны полу. Вернитесь в исходное положение и повторите упражнение.", imageBig: UIImage(named: "squatsSumo"), imageSmall: UIImage(named: "Сумо-приседания")),
        Lesson(name: "Сумо-приседания", time: nil, counts: 12, text: "Встаньте ровно, ноги на ширине 15-30 сантиметров. \n\nОпускайтесь до тех пор, пока бедра не станут параллельны полу. Вернитесь в исходное положение и повторите упражнение.", imageBig: UIImage(named: "squatsSumo"), imageSmall: UIImage(named: "Сумо-приседания")),
        Lesson(name: "Низкий старт", time: nil, counts: 10, text: "Из положения стоя опуститесь на корточки и упритесь руками в землю. \n\nОдновременно выпрямите руки и ноги и сразу же вернитесь в положение «на корточках».Затем выпрыгните вверх. \n\n«Низкий старт»- это аэробное силовое упражнение для мышц всего тела.", imageBig: UIImage(named: "startLow"), imageSmall: UIImage(named: "Низкий старт")),
        Lesson(name: "Пожарный кран влево", time: nil, counts: 12, text: "И.п. стоя на четвереньках, колени строго под бедрами, руки под плечами. \n\nПоднимите пятку левой ноги к ягодице и как можно дальше вытяните колено в сторону.", imageBig: UIImage(named: "fireHydrantLeft"), imageSmall: UIImage(named: "Диагональная «планка»")),
        Lesson(name: "Пожарный кран вправо", time: nil, counts: 12, text: "И.п. стоя на четвереньках, колени строго под бедрами, руки под плечами. \n\nПоднимите пятку правой ноги к ягодице и как можно дальше вытяните колено в сторону.", imageBig: UIImage(named: "fireHydrantright"), imageSmall: UIImage(named: "Диагональная «планка»")),
        Lesson(name: "Пожарный кран влево", time: nil, counts: 12, text: "И.п. стоя на четвереньках, колени строго под бедрами, руки под плечами. \n\nПоднимите пятку левой ноги к ягодице и как можно дальше вытяните колено в сторону.", imageBig: UIImage(named: "fireHydrantLeft"), imageSmall: UIImage(named: "Диагональная «планка»")),
        Lesson(name: "Пожарный кран вправо", time: nil, counts: 12, text: "И.п. стоя на четвереньках, колени строго под бедрами, руки под плечами. \n\nПоднимите пятку правой ноги к ягодице и как можно дальше вытяните колено в сторону.", imageBig: UIImage(named: "fireHydrantright"), imageSmall: UIImage(named: "Диагональная «планка»")),
        Lesson(name: "Пожарный кран влево", time: nil, counts: 12, text: "И.п. стоя на четвереньках, колени строго под бедрами, руки под плечами. \n\nПоднимите пятку левой ноги к ягодице и как можно дальше вытяните колено в сторону.", imageBig: UIImage(named: "fireHydrantLeft"), imageSmall: UIImage(named: "Диагональная «планка»")),
        Lesson(name: "Пожарный кран вправо", time: nil, counts: 12, text: "И.п. стоя на четвереньках, колени строго под бедрами, руки под плечами. \n\nПоднимите пятку правой ноги к ягодице и как можно дальше вытяните колено в сторону.", imageBig: UIImage(named: "fireHydrantright"), imageSmall: UIImage(named: "Диагональная «планка»")),
        Lesson(name: "Приседания", time: nil, counts: 12, text: "Ноги на ширине плеч, руки вытянуты перед собой. Опускайтесь до тех пор, пока бедра не будут параллельны полу. \n\nПри выполнении упражнения колени должны быть направлены туда же, куда направлены носки ног. Вернитесь в исходное положение.Повторите нужное количество раз. \n\nУпражнение нагружает мышцы передней и задней поверхности бедра, ягодицы, нижней части корпуса.", imageBig: UIImage(named: "Squats"), imageSmall: UIImage(named: "Приседания")),
        Lesson(name: "Приседания", time: nil, counts: 12, text: "Ноги на ширине плеч, руки вытянуты перед собой. Опускайтесь до тех пор, пока бедра не будут паралельны полу. \n\nПри выполнении упражнения колени должны быть направлены туда же, куда направлены носки ног. Вернитесь в исходное положение.Повторите нужное количество раз.  \n\nУпражнение нагружает мышцы передней и задней поверхности бедра, ягодицы, нижней части корпуса.", imageBig: UIImage(named: "Squats"), imageSmall: UIImage(named: "Приседания")),
        Lesson(name: "Приседания", time: nil, counts: 12, text: "Ноги на ширине плеч, руки вытянуты перед собой. Опускайтесь до тех пор, пока бедра не будут параллельно полу. \n\nПри выполнении упражнения колени должны быть направлены туда же, куда направлены носки ног. Вернитесь в исходное положение.Повторите нужное количество раз. \n\nУпражнение нагружает мышцы передней и задней поверхности бедра, ягодицы, нижней части корпуса.", imageBig: UIImage(named: "Squats"), imageSmall: UIImage(named: "Приседания")),
        Lesson(name: "Растяжка четырехглавой мышцы у стены (левая нога)", time: 30, counts: nil, text: "Встаньте ровно, правая рука на стене. Согните левую ногу в колене и обхватите щиколотку или ступню левой рукой. Подтяните левую голень к левому бедру. Оставайтесь в этом положении.", imageBig: UIImage(named: "Stretch(left leg)"), imageSmall: UIImage(named: "Растяжка четырехглавой")),
        Lesson(name: "Растяжка четырехглавой мышцы у стены (правая нога)", time: 30, counts: nil, text: "Встаньте ровно, левая рука на стене. Согните правую ногу в колене и обхватите щиколотку или ступню правой  рукой. Подтяните правую голень к правому бедру. Оставайтесь в этом положении.", imageBig: UIImage(named: "Stretch(right leg)"), imageSmall: UIImage(named: "Растяжка четырехглавой")),
        Lesson(name: "Растяжка «левое колено к груди»", time: 30, counts: nil, text: "Ложитесь спиной на пол, ноги вытянуты. Поднимите левое колено и схватите его обеими руками. \n\nПотяните левое колено как можно ближе к груди, прямая правая нога при этом должна лежать на полу.Оставайтесь в этом положении несколько секунд.", imageBig: UIImage(named: "LeftKneeToChestStretch"), imageSmall: UIImage(named: "workout-5")),
        Lesson(name: "Растяжка «правое колено к груди»", time: 30, counts: nil, text: "Ложитесь спиной на пол, ноги вытянуты. Поднимите правое колено и схватите его обеими руками. \n\nПотяните правое колено как можно ближе к груди, прямая левая нога при этом должна лежать на полу.Оставайтесь в этом положении несколько секунд.", imageBig: UIImage(named: "RightKneeToChestStretch"), imageSmall: UIImage(named: "workout-5"))
        
    ])
    // MARK: - Плечи и спина продвинутый.
    ///Плечи и спина продвинутый - advancedShouldersAndBack
    static let advancedShouldersAndBack = Workouts(type: .advanced, image: UIImage(named: "advancedShouldersAndBack"), girlImage: UIImage(named: "спина3"), name: "Плечи и спина", lessons: [
        Lesson(name: "Прыжки", time: 30, counts: nil, text: "Ноги вместе, руки вдоль корпуса. Прыжком разведите ноги, одновременно поднимаю руки в стороны до положения над головой. Прыжком верните в исходное положение. \n\nПовторите нужное количество раз. Упражнение нагружает все крупные группы мышц, укрепляя все тело.", imageBig: UIImage(named: "Jumping"), imageSmall: UIImage(named: "Прыжки")),
        
        Lesson(name: "Гиперэкстензии", time: nil, counts: 14, text: "Ложитесь на живот, пыльцы ног касаются пола, подбородок лежит на кистях рук. \n\nПоднимите грудь от пола как можно выше. Оставайтесь в этом положении несколько секунд, затем вернитесь в исходное положение.Повторите упражнение.", imageBig: UIImage(named: "Hyperextensions"), imageSmall: UIImage(named: "Гиперэкстензии")),
        Lesson(name: "Отжимания с упором сзади", time: nil, counts: 16, text: "Исходное положение – на четвереньках, колени под ягодицами, руки под плечами. \n\nПоднимите ноги на стул или скамью и выполняйте отжимания преимущественно силой рук. \n\nНе забывайте держать корпус прямо.", imageBig: UIImage(named: "Push-upsWithBackSupport"), imageSmall: UIImage(named: "Отжимания с упором сзади")),
        Lesson(name: "Отжимания с упором сзади", time: nil, counts: 16, text: "Исходное положение – на четвереньках, колени под ягодицами, руки под плечами. \n\nПоднимите ноги на стул или скамью и выполняйте отжимания преимущественно силой рук. \n\nНе забывайте держать корпус прямо.", imageBig: UIImage(named: "Push-upsWithBackSupport"), imageSmall: UIImage(named: "Отжимания с упором сзади")),
        Lesson(name: "Гиперэкстензии", time: nil, counts: 14, text: "Ложитесь на живот, пыльцы ног касаются пола, подбородок лежит на кистях рук. \n\nПоднимите грудь от пола как можно выше. Оставайтесь в этом положении несколько секунд, затем вернитесь в исходное положение.Повторите упражнение.", imageBig: UIImage(named: "Hyperextensions"), imageSmall: UIImage(named: "Гиперэкстензии")),
        Lesson(name: "Поза кошки", time: 30, counts: nil, text: "Начальное положение – на четвереньках, колени под ягодицами, ладони прямо под плечами. \n\nДелая вдох, опустите живот, разверните плечи и поднимите голову. \n\nДелая выдох, выгните спину наверх и опустите голову. Повторите упражнение.", imageBig: UIImage(named: "CatPose"), imageSmall: UIImage(named: "yoga-pose-2")),
        Lesson(name: "Гиперэкстензии", time: nil, counts: 14, text: "Ложитесь на живот, пыльцы ног касаются пола, подбородок лежит на кистях рук. \n\nПоднимите грудь от пола как можно выше. Оставайтесь в этом положении несколько секунд, затем вернитесь в исходное положение. \n\nПовторите упражнение.", imageBig: UIImage(named: "Hyperextensions"), imageSmall: UIImage(named: "Гиперэкстензии")),
        Lesson(name: "Отжимания с опорой впереди", time: nil, counts: 16, text: "Исходное положение – обычное положение для отжиманий, но с руками на стуле или скамье. \n\nВыполняйте отжимания силой рук. Не забывайте держать корпус прямо.", imageBig: UIImage(named: "FrontPushUp"), imageSmall: UIImage(named: "Отжимания с опорой впереди")),
        Lesson(name: "Наклоны вперед", time: nil, counts: 10, text: "Встаньте ровно, ноги на ширине плеч. \n\nПодайте бедра назад и наклоните прямой корпус вперед. Медленно вернитесь в исходное положение, повторите упражнение.", imageBig: UIImage(named: "forwardLeans"), imageSmall: UIImage(named: "Наклоны вперед")),
        Lesson(name: "Отжимания со смещением", time: nil, counts: 15, text: "Примите упор лежа. Опуститесь на руках. В нижней точке переместите корпус влево, затем вправо. \n\nПоднимитесь на руках. Повторите упражнение.", imageBig: UIImage(named: "Push-upsWithOffset"), imageSmall: UIImage(named: "Отжимания от пола")),
        Lesson(name: "Отжимания со смещением", time: nil, counts: 15, text: "Примите упор лежа. Опуститесь на руках. В нижней точке переместите корпус влево, затем вправо. \n\nПоднимитесь на руках. Повторите упражнение.", imageBig: UIImage(named: "Push-upsWithOffset"), imageSmall: UIImage(named: "Отжимания от пола")),
        Lesson(name: "Отжимания со смещением", time: nil, counts: 15, text: "Примите упор лежа. Опуститесь на руках. В нижней точке переместите корпус влево, затем вправо. \n\nПоднимитесь на руках. Повторите упражнение.", imageBig: UIImage(named: "Push-upsWithOffset"), imageSmall: UIImage(named: "Отжимания от пола")),
        Lesson(name: "Поза ребенка", time: 30, counts: nil, text: "Начальное положение – с коленями и ладонями на полу. \n\nСлегка вытяните руки вперед, раздвиньте колени и сведите вместе ступни. Вдохните, затем выдохните и подайте корпус назад. Постарайтесь сделать так, чтобы ягодицы касались пяток. \n\nРасслабьте локти, коснитесь лбом пола и постарайтесь опустить грудь к полу. Оставайтесь в этом положении.", imageBig: UIImage(named: "ChildPose"), imageSmall: UIImage(named: "yoga-pose")),
        Lesson(name: "Наклоны вперед", time: nil, counts: 10, text: "Встаньте ровно, ноги на ширине плеч. \n\nПодайте бедра назад и наклоните прямой корпус вперед. Медленно вернитесь в исходное положение, повторите упражнение.", imageBig: UIImage(named: "forwardLeans"), imageSmall: UIImage(named: "Наклоны вперед"))
    ])
}

